### ISSUE TITLE
Unable to click on nodes outside of session window size

### ISSUE THREAD

**Issue by whw** [keathley/wallaby#100]
#### Setup

We have a page where clicking on a button will cause other buttons to appear further down the page.
#### Problem

`Wallaby.Node.Find` would be unable to find the buttons that appeared further down the page. Originally I thought it was a problem with the nodes not rendering in time, but I could see >part< of buttons inside the failure screenshots.
#### Workaround Solution

Increasing the window size for the session fixed the problem

This behavior seems odd though - one would think that phantom would be able to click anything on the page regardless of if it is scrolled off.

**Comment by keathley** [comment]
Can you create a gist or a sample repo that reproduces this issue? Finding should scroll the element into view.

**Comment by whw** [comment]
Never got around to creating a gist, and recently we updated our code that hit this and it appears the issue has gone away. Closing.
