### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by rpwatkins** [keathley/wallaby#102]
Is there any chance this can be modified to run on Windows.  The shall script requires a bash environment, as I understand it. Could that not be replaced with a similar batch file?

**Comment by keathley** [comment]
I'd love to have better support for windows. Unfortunately I don't have a windows machine to test against atm. If you want to submit a patch I'd be happy to review it.

**Comment by keathley** [comment]
To add a bit more information here. What you would need to do is translate: https://github.com/keathley/wallaby/blob/master/priv/run_phantom.sh into something that windows understands.

**Comment by texjim** [comment]
How about the following Powershell script (run_phantom.ps1)?

```powershell
$a = $MyInvocation.UnboundArguments
$p = $a[1..($a.length -1)]
$process = Start-Process $a[0] -ArgumentList "$p" -PassThru
$waitforcr = Read-Host
Stop-Process $process.Id
```

**Comment by chowevtfy** [comment]
Using that script, we successfully tested running Wallaby under Windows. All the tests passed, but zombie processes were left behind. The powershell script is intended to prevent that, so a little bit more work is needed for this to be ready.

**Comment by keathley** [comment]
You might have to pass `-Force` to the `Stop-Process` call based on this: https://technet.microsoft.com/en-us/library/hh849781.aspx.

**Comment by chowevtfy** [comment]
Ah, yes, [we've tried that](https://github.com/vertify/wallaby/blob/master/priv/run_phantom.ps1#L5). You can see how we're calling into powershell [here](https://github.com/vertify/wallaby/blob/master/lib/wallaby/server.ex#L36). I think that using the `-Command` option may be causing it to spawn a second instance of powershell to run the script. l'm not sure exactly what problems that could cause yet.

**Comment by keathley** [comment]
I'm not super familiar with powershell. But, is it possible that the command is running the script, then exiting, orphaning the script? Have you tried removing the `-Command` flag?

**Comment by zolrath** [comment]
Any progress in getting Windows support working properly?
Have a few developers shifting between C# and Elixir and would love to have Wallaby run on everyone's machine.

**Comment by texjim** [comment]
@zolrath  Take a look at our fork ( https://github.com/vertify/wallaby ).   All of the 145 unit tests pass on my Windows 10 box, but we are running a strange issue where you have to hit Ctrl-C or Enter a few times for the shell to be ready to accept commands after the tests run.    When I look at the process table, the phantonjs processes are still there until I hit Ctrl-C...then they all close and the shell is ready to take commands again.

**Comment by keathley** [comment]
I tried to work on this a bit with a friend on their windows 10 box. We weren't able to get your fork working @texjim. It seemed like the port that we use to manage an individual phantom instance wasn't getting any data. Have you seen anything like that?

**Comment by texjim** [comment]
What version of Powershell are you using?   

```shell
PS C:\wallaby> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      0      10586  672
```

If I'm not mistaken when I had an older version loaded it did give me issues.   Here are the version numbers for what I have loaded:

```shell
PS C:\wallaby> choco list --local-only
chocolatey 0.9.9.11
elixir 1.3.4
erlang 19.0
PhantomJS 2.1.1
PowerShell 5.0.10586.20151218
```

**Comment by keathley** [comment]
I'll double check.

**Comment by keathley** [comment]
I just wanted to follow up on this to see if anyone had had any luck getting wallaby to work on windows. I also didn't know if it might be easier now that we are supporting chrome and chromedriver.

**Comment by keathley** [comment]
I'm going to close this for now since I don't have any other actionable steps to take. If anyone has further information please feel free to re-open.
