### ISSUE TITLE
Attach files via wallaby

### ISSUE THREAD

**Issue by asiniy** [keathley/wallaby#103]
There is a lot of ways to interact with the forms, but I haven't found a way to interact with website by attach some files to the file fields. I think this should be implemented

@keathley WDYT?

**Comment by keathley** [comment]
There is an `attach_file` action: https://hexdocs.pm/wallaby/Wallaby.DSL.Actions.html#attach_file/3.

Its included in the DSL documentation but needs to be added to the README.

**Comment by asiniy** [comment]
Thx!
