### ISSUE TITLE
Waiting for async code without narrowing find scope

### ISSUE THREAD

**Issue by opsb** [keathley/wallaby#104]
The advice for async code is to `find` something on the page that will be visible once the async action has completed (`find` will block for up to 3 secs by default). This works great but there's a problem in that `find` is chainable and narrows the scope of any finds further on in the chain.

```
    session
    |> visit("http://localhost:28080/?authAdapter=test&apiBasePath=%2F%2Flocalhost%3A4001%2F")
    |> fill_in("Add new feed", with: "Lobby")
    |> send_keys([:enter])
    |> find(".side-nav__list-item a", text: "Lobby") # wait for async action to complete
    |> fill_in("What's got you thinking?", with: "hello")
```

The last line fails because in this scenario the textarea that it's attempting to fill in is not inside the scope specified by the previous find, ".side-nav__list-item a", text: "Lobby".

There's a few options here:

**1) Introduce a command that waits for something to appear**

`|> waitFor(".side-nav__list-item a", text: "Lobby") # wait for async action to complete`

**2) Allow the find scope to be reset**

```
    session
    |> visit("http://localhost:28080/?authAdapter=test&apiBasePath=%2F%2Flocalhost%3A4001%2F")
    |> fill_in("Add new feed", with: "Lobby")
    |> send_keys([:enter])
    |> find(".side-nav__list-item a", text: "Lobby") # wait for async action to complete
    |> resetScope
    |> fill_in("What's got you thinking?", with: "hello")
```

**3) Don't make `find` chainable**
...seeing as you can always express chained finds with a single find

**4) Introduce something like `tap`**

```
session
|> visit("/page.html")
|> tap(fn session -> 
  session
  |> users
  |> find(".user", count: 3)
  |> List.first
  |> find(".user-name")
end)
|> continue with original scope
```

**Comment by opsb** [comment]
Here's a couple of the implementations implementations, happy to put a PR together if either is desired.
```
  def wait_for(session, locator, options) do
    session |> find(locator, options)
    session
  end

  def wait_for(session, locator) do
    session |> find(locator)
    session
  end
```

```
  def tap(session, callback) do
    callback.(session)
    session
  end
```

**Comment by keathley** [comment]
I like the idea of `wait_until`. The other solutions strike me as something that could be solved by breaking up the piped operations. If you want to submit a PR for `wait_until` that would be rad :smile:.

**Comment by keathley** [comment]
This has now been implemented as part of find. I'm going to close this issue. We can continue the discussion about `wait_until` in #105.
