### ISSUE TITLE
Only start phantomjs when running acceptance tests

### ISSUE THREAD

**Issue by joshuataylor** [keathley/wallaby#107]
When running a test case that doesn't rely on wallaby, is it possible to not start PhantomJS in this case?

**Comment by joshuataylor** [comment]
Right now I just set the `pool_size` to 0.

**Comment by keathley** [comment]
You can move the `{:ok, _} = Application.ensure_all_started(:wallaby)` from your `test_helper.exs` into a `setup_all` in your `AcceptanceCase` test case.

**Comment by padde** [comment]
@keathley might that be a useful addition to the setup info in the README?

**Comment by keathley** [comment]
That seems reasonable for now. Long term we could configure poolboy to start with 0 phantoms started and spin them up as needed until we hit the max poolsize. That way the end user doesn't have to mess with this configuration. If someone wants to submit a PR for either fix that would be great. I'm going to close this for now.
