### ISSUE TITLE
Support for multiple `Repo`s

### ISSUE THREAD

**Issue by NobbZ** [keathley/wallaby#109]
It seems to be quite common to have multiple OTP-Apps dealing with their own `Repo`s in in umbrella application.

According to a short talk to @keathley, this is currently not supported by wallaby.

An example of such an umbrella application is wojtekmach's [acme_bank](https://github.com/wojtekmach/acme_bank) from ExConf '16. It has a Repo at least in the sub-apps `bank` and `auth`.

**Comment by viniciussbs** [comment]
@NobbZ [You can pass more than one repo to `metadata_for`](https://github.com/phoenixframework/phoenix_ecto/blob/master/lib/phoenix_ecto/sql/sandbox.ex#L50-L58). This should work:

```elixir
repos = [MyApp.RepoA, MyApp.RepoB, OtherApp.Repo]
metadata = Phoenix.Ecto.SQL.Sandbox.metadata_for(repos, self())

{:ok, session} = Wallaby.start_session(metadata: metadata)
```

**Comment by StevenXL** [comment]
@viniciussbs that suggestion didn't work for me; maybe there are other steps that need to change that we are not considering?

In the meantime, any solution to this? I myself have an app structured like @NobbZ mentioned, with multiple repos.

**Comment by NobbZ** [comment]
I didn't follow up on this. Shortly after posting the issue I decided to do it the classic way without umbrella. So I do only have a single Repo.

**Comment by viniciussbs** [comment]
@StevenXL You need to checkout connections:

```elixir
:ok = Ecto.Adapters.SQL.Sandbox.checkout(MyApp.RepoA)
:ok = Ecto.Adapters.SQL.Sandbox.checkout(MyApp.RepoB)
:ok = Ecto.Adapters.SQL.Sandbox.checkout(OtherApp.Repo)
```

I don't remember if there are more steps to follow because I'm not using this anymore. But, if you have Phoenix Channels, check this [issue](https://github.com/phoenixframework/phoenix_ecto/issues/72).

**Comment by st23am** [comment]
@viniciussbs  do you check the repos before after the config you listed previous?

**Comment by keathley** [comment]
@viniciussbs has the correct answer here. Going to close this.
