### ISSUE TITLE
console.log sent to stdout

### ISSUE THREAD

**Issue by seangeo** [keathley/wallaby#113]
Hi, with the latest version of wallaby it seems that console.log output is sent to stdout. Is there a way to control this, e.g. turn it off to direct it to a file? Thanks.

**Comment by keathley** [comment]
I just pushed a new version (v0.14.0) that includes a `js_logger` config option. If you set that to `nil` it will disable js console logging. You can also set `js_logger` to a different IO device (like a file) and it will direct output there.

Lemme know if you have any other issues @seangeo.
