### ISSUE TITLE
Http Cache isn't cleared

### ISSUE THREAD

**Issue by smdern** [keathley/wallaby#116]
I've run into an issue where cache-control is breaking some tests. Looks like `page.clearMemoryCache()` between runs

**Comment by smdern** [comment]
After doing a bit more looking into this. It appears that this isn't going to be very straightforward. It looks like ghostdriver doesn't have a `clearMemoryCache()` endpoint since it's a newer feature.

**Comment by keathley** [comment]
Sorry about that @smdern. Can you explain what the specific problem was?

**Comment by smdern** [comment]
@keathley I'm running a series of tests that require some seed data to exist in the DB. I insert the models as part of each test setup, but the endpoint that returns the list of models adds a cache-control header. The problem is that the `id` that is presented is different depending on which test ran first and causes subsequent tests (which tries to insert a model that associates to those ids) to fail.

It seems like the most straightforward way to handle this is to disable cache-control in the test environment, but ideally there could be a way to clear the cache between tests. It looks like phantomjs v2+ has such a feature which has `clearMemoryCache()`. After creating this issue I thought I'd try to open a PR but it looks like ghostdriver (which implements the wire protocol for phantomjs giving us the REST interface) hasn't been touched much since phantom 1.9.

**Comment by smdern** [comment]
scenario would be

test 1
 - inserts model(uniqueName=foo returns ID=1)
 - controller returns cache-control response with model id

test 2
  - inserts model(unqiueName=foo) (returns ID=2)
  - doesn't hit controller for list of ids because of cache-control
  - tries to create model with association to the model but w/ ID=1 because of cached response
  - insert fails because entry with ID=1 doesn't exist
