### ISSUE TITLE
PhantomJS multiple instances still running after ctrl-c

### ISSUE THREAD

**Issue by nii236** [keathley/wallaby#118]
I stopped my test suite with ctrl-c and turns out graceful shutdown isn't implemented with regards to phantom JS instances. Roughly 10 were still alive and chugging along, killing my CPU/RAM until I noticed it.

To remove these I had to kill these one by one manually, or to run the test suite again from start to finish.

Is there any way to kill phantomJS instances on an interrupt signal during running tests?

**Comment by keathley** [comment]
Graceful shutdown *should* be working. Can you give me some more info about the platform you're running on, etc.?

**Comment by nii236** [comment]
I ran it a few more times and graceful shutdown worked perfectly fine. If and when I am able to replicate the bug I will record it and create a new issue.

Thanks for the response!

**Comment by keathley** [comment]
Sorry it caused you an issue. Lemme know if you manage to recreate it :+1:
