### ISSUE TITLE
Testing with brunch

### ISSUE THREAD

**Issue by pauloancheta** [keathley/wallaby#125]
http://www.phoenixframework.org/docs/static-assets#section-modules

I have been following phoenix guides into adding javascript into my app and have found that this causes unexpected errors while testing. Wallaby does not provide any errors on my local machine but it does on Travis.

I have fiddled with the testing suite and was able to replicate the exact error that I get from Travis

```html
<!DOCTYPE HTML>
<html>
  <head>
    <script>require("web/static/js/app").App.run()</script>
  </head>
  <body>
  </body>
</html>
```

```elixir
test "it captures a require error", %{session: session, server: server} do
  fun = fn ->
    session
    |> visit(server.base_url <> "/require_error.html")
  end

  assert capture_io(fun) == "error"
end
```

This test will result to:
```
 1) test it captures a require error (Wallaby.Phantom.Driver.JSErrorsTest)
     test/wallaby/phantom/driver/js_errors_test.exs:37
     ** (Wallaby.JSError) There was an uncaught javascript error:

     ReferenceError: Can't find variable: require
       global code (http://localhost:54863//require_error.html:5)
```

My current work-around was to suppress javascript errors.

**Comment by keathley** [comment]
Thanks for providing the steps to re-create this @pauloancheta! It seems to me like your assets aren't being bundled on travis if you're seeing an error about `require` not being defined. Is your brunch config the stock config that phoenix generates? Is it possible that travis isn't compiling your assets before it runs your tests?

**Comment by keathley** [comment]
@pauloancheta do you happen to have an update on this? If not would you mind if I closed the issue for now?

**Comment by pauloancheta** [comment]
I continued with my work-around in place and haven't worked on this part of my app again. Will reopen the issue once I encounter it again and have an update

**Comment by keathley** [comment]
Thanks!
