### ISSUE TITLE
Methods for not-finding nodes or content

### ISSUE THREAD

**Issue by bomatson** [keathley/wallaby#13]
In order to help write specs where nodes are removed from the DOM, we could use a method where it resolves when the pattern is not found. This would kinda be the opposite of find(pattern, count: x)

Wishful use case:

```elixir
session
  |> click("remove-button")
  |> find(".new_object", count: 0)

#or
  |> wait_until_gone(".new_object")
```

Where a failing spec would be like:

`Expected to find 'new-object' with count 0 but found 1 node`

**Comment by keathley** [comment]
Would a matcher like `has_no_css?` work? The goal of this method is to assert that the node isn't visible or isn't present on the page right? It would kinda make sense to me that it should be a predicate if thats the case. Under the hood it could use the same retry logic that finding does to block until the element has been removed.

**Comment by eiseneker** [comment]
That works! :+1:

**Comment by keathley** [comment]
Opened a PR to support this
