### ISSUE TITLE
add a `data` tag query

### ISSUE THREAD

**Issue by keathley** [keathley/wallaby#136]
A common way to annotate DOM elements is with a `data` tag. It would be very convenient to have a `data` query that allowed users to specify a tag name and a value.

**Comment by aellispierce** [comment]
I can give this a shot

**Comment by PragTob** [comment]
Hey, please do! :)

Let us know if you have any sorts of questions, happy to help! :tada:

**Comment by germsvel** [comment]
I took a stab at this in #401 . Let me know if this wasn't the way to go with this. Happy to amend or close the PR. Thanks for maintaining Wallaby!
