### ISSUE TITLE
Allow "text" to receive more than one node

### ISSUE THREAD

**Issue by bomatson** [keathley/wallaby#14]
it would be nice to have some way to have a collection of wallaby nodes be able to return a blob (or array!) of text:

```elixir
project_text = 
  session
  |> find(".project", count: 2)
  |> text

# project_text would be "project 1 project 2" or ["project 1", "project 2"]
```

**Comment by keathley** [comment]
You can achieve the same thing this way: 

```elixir
project_text = 
  session
  |> find(".project", count: 2)
  |> Enum.map(&text/1)
```

**Comment by keathley** [comment]
For now I'd rather be more explicit with lists. I'm happy to revisit this in the future.
