### ISSUE TITLE
Release 0.16.0 not available in hex?

### ISSUE THREAD

**Issue by navinpeiris** [keathley/wallaby#149]
Heya @keathley, just noticed that the repo has been updated to version 0.16.0 along with the release etc., but the latest version available in hex is still 0.15.0.

Just wanted to see if this was on purpose?

**Comment by PragTob** [comment]
Here wondering the same thing - just wanted to comment into our slack "Write ALL THE INTEGRATION TESTS NOW" :)

**Comment by keathley** [comment]
Yeah sorry about that. I discovered an issue with some of the deprecation warnings. I'm going to release 0.16.0 and then 0.16.1 write behind it. That way people can upgrade directly to 0.16.1 and not experience the bug ;). Should be up soon.

**Comment by keathley** [comment]
Version 0.16.0 and 0.16.1 have both been published to hex!

**Comment by navinpeiris** [comment]
Awesome, thanks a bunch @keathley! Loving the new API btw 👍
