### ISSUE TITLE
Ambiguous matches

### ISSUE THREAD

**Issue by bomatson** [keathley/wallaby#15]
We noticed some ambiguous match problems when using #find for an element - it will timeout instead of returning an error:

```elixir
session |> find(".project")

# If there are two projects, this will hang
```

**Comment by keathley** [comment]
So this returns a `Wallaby.ElementNotFound` error? Or does it not actually catch the error correctly?

**Comment by eiseneker** [comment]
Actually, looks like the behavior may have changed in the last day or so? We journaled this problem on Monday, but now it returns a Wallaby.AmbiguousMatch error in those cases, which is great. Good to close this.
