### ISSUE TITLE
assert_has/refute_has helpers

### ISSUE THREAD

**Issue by PragTob** [keathley/wallaby#159]
This was briefly touched upon in #158 (brought up by @knewter ) - if we want to have some custom assert_* helpers in wallaby specifically `assert_has`/`refute_has`

I think it's a good idea and an easy implementation, I currently have my custom helpers like this:

```elixir
    defp assert_has(parent, query) do
      assert has?(parent, query)
      parent
    end
```

Among having an assert ready, it allows to write assertions nicely as part of a pipe by returning the parent element:

```elixir
      session
      |> visit("/")
      |> take_screenshot
      |> assert_has(@login_button)
      |> login_as(me)
      |> take_screenshot
      |> assert_has_no(@login_button)
      |> assert_has(@logout_button)
      |> assert_text(@page_content, "Welcome")

```

(note right now I still have one valled `assert_has_no` but realized it's a bad idea and will change to `refute_has`)

I wanna finish up my work tomorrow and then PR these helpers and maybe others I have over the weekend/discuss them here as I feel they might be beneficial for a lot of people :)

**Comment by keathley** [comment]
The more I've thought about it the more I like `assert_has?` and `refute_has?`. It would be great to make both of those chainable and we could correctly take screenshots on failures, etc.

Should we include helpers besides `assert_has?` and `refute_has?` I feel like we should be able to check everything we need to with a combination of those 2 assertions and the query engine but maybe I'm wrong.

**Comment by PragTob** [comment]
So far I found that they can cover everything I'd like them to, people might like to have stuff like `assert_has_css(parent, css_string)` but I feel that predefined queries via `Query.css` are the better interface.

So with the cool new `Query`/`Action` distinction (:heart: that by the way but you know :) ) this should legitimately cover everything, so far.

If needbe, other things can always be added later :)

**Comment by keathley** [comment]
That sounds good to me.

Should we use macros for those helpers so that the stack traces are more meaningful to the end user?

**Comment by PragTob** [comment]
Huh, good question gotta admit I haven't played around with macros a lot yet and usually try to do the simplest thing that works :) I'll give it a shot and compare stack traces on my end and put them in the PR.

PR might be a bit delay as I seem to have released a slightly bugged simplecov version the other day and wanna get it fixed first, ETA still hopeful on this weekend though :)
