### ISSUE TITLE
Is `AcceptanceCase` really the right term?

### ISSUE THREAD

**Issue by padde** [keathley/wallaby#167]
According to the [Wikipedia article on software testing](https://en.wikipedia.org/wiki/Software_testing#Acceptance_testing),

> Acceptance testing can mean one of two things:
>
> 1. A smoke test is used as an acceptance test prior to introducing a new build to the main testing process, i.e., before integration or regression.
> 2. Acceptance testing performed by the customer, often in their lab environment on their own hardware, is known as user acceptance testing (UAT). Acceptance testing may be performed as part of the hand-off process between any two phases of development.

This leads me to the conclusion that `AcceptanceCase` is not really the right term for what we're doing with Wallaby.

Maybe one the following alternatives would be a better fit:

* `IntegrationCase`
* `EndToEndCase`
* `BrowserCase`
* `FunctionalCase`
* `SystemCase`

`IntegrationCase` sounds better IMO, but integration testing also refers to testing just parts of a system in conjunction, as opposed to unit testing (just one function) or system testing (the entire thing).

Both `EndToEndCase` and `BrowserCase` would refer to the fact that we are testing through the browser, exercising the entire stack end-to-end.

`FunctionalCase` is not really my favorite, since the term "functional test" seems to be used on a different level than the others. It's more a question of "do we test user requirements directly" (functional) or "do we test some part of the system that is not really important from a user's perspective". On top of that, the term "functional" might be too confusing. Nevertheless, I've sometimes seen "functional test" used as a term for browser tests, so I dropped it in here.

Finally, `SystemCase` would mean that we are testing the entire system, not just parts thereof.

Discuss! 😉  What are your thoughts?

**Comment by padde** [comment]
Reading the Wallaby source code, I found that internally the term `SessionCase` is used, which I think is a good name. How about using this in the documentation instead?

**Comment by PragTob** [comment]
Sessioncase is a bit weird imo, as it's really close to `ConnCase` which is one of the phoenix standards.

I like `AcceptanceCase` as "Acceptance tests" is also how I commonly refer to these tests, so it's natural to me but there are a lot of different uses for the words of them (worst of them all is integration).

From the proposed solutions EndToEnd/Browser seem to fit best but I'm also happy with Acceptance.

**Comment by keathley** [comment]
`SessionCase` is in the Wallaby codebase because it provides a `session`. But I don't think thats what we want to expose to the outside world. I'm ok with `AcceptanceCase` but I'd be OK with `BrowserCase` or potentially `FeatureCase`. I typically treat our wallaby tests as "feature" tests. Meaning that they exercise a "feature" of the application.

**Comment by PragTob** [comment]
I like feature as well :)

**Comment by keathley** [comment]
If someone wants to update the README to use `FeatureCase` then that would be great. Otherwise I'll try to get to it when I can 👍 .
