### ISSUE TITLE
Return order from `find` is inconsistent

### ISSUE THREAD

**Issue by bomatson** [keathley/wallaby#17]
The #find method for a given selector which returns more than one result; it may not return these elements in the strictly-same order (expected to always be ordered by the DOM). This was our work-around:

``` elixir
projects =
  session
    |> sign_in
    |> find(".project", count: 2)

first_project = List.first(projects)

project_text =
  projects
    |> Enum.map(&text(&1))
    |> Enum.sort

assert project_text == ["Initech", "The Petty Marsh"]
```

**Comment by keathley** [comment]
I can't re-create this at this point so I'm going to close it for now.
