### ISSUE TITLE
Docs/spec confusing for functions with return type parent

### ISSUE THREAD

**Issue by arigoins** [keathley/wallaby#172]
Here's an example of what I was trying to do:
```
session
|> visit(foo_path(Endpoint, :new))
|> execute_script("...")
|> take_screenshot()
```
This raises `(UndefinedFunctionError) function nil.url/0 is undefined or private` and wondering what's that about. I had to look at the source to figure out that `execute_script` returns the value and not the session even though the spec `execute_script(parent, String.t, list) :: parent` makes me think it would return the session.

Side note, it would be nice to have functions like `execute_script` be pipe-able or a pipe-able version  that ignores the return value like my example. For now I'm doing:
```
def execute_script_pipe(session, script, arguments \\ []) do
   {:ok, _} = Driver.execute_script(session, script, arguments)
   session
end
```

**Comment by PragTob** [comment]
Thanks for the issue report!

Definitely! That execute_script claims to return `parent` is a bug :frowning: 

Added enhancement tag though because I agree that we want to have a pipable version of that... no idea how to make a good name differentiation between the two, as we also need to have a method that grabs the return value ...

Any suggestions?

**Comment by keathley** [comment]
What if we use a similar pattern to `find`? `execute_script/1` would return the parent so that it can be chained. `execute_script/2` can accept a callback that would return the value to the user?

Something like:

```elixir
session
|> execute_script("var a = 1337; return a;", fn(value) -> assert value == 1337 end)
|> take_screenshot()
```

What do y'all think?

**Comment by PragTob** [comment]
LGTM :+1:
