### ISSUE TITLE
Sessions not being cleaned up correctly when tests end

### ISSUE THREAD

**Issue by keathley** [keathley/wallaby#174]
Unless the session is explicitly "ended" when the test ends the sessions in phantom are being left open. I discovered this when my phoenix server started receiving duplicate messages from 2 browsers. What was happening is that the first test ran, connected to the channel, and executed the test. When the test ended the phantom was being checked back in but the session wasn't being deleted from the phantom. You normally wouldn't see this sort of issue. It only cropped up because we drive several user actions from external devices and those devices broadcast their data over a separate phoenix channel to all connected clients (which in practice is only ever 1 client).

You can fix this issue by explicitly calling `Wallaby.end_session(session)` in your setup block like this:

```elixir
setup %{session: session} do
  on_exit fn ->
    Wallaby.end_session(session)
  end
end
```

But, we should account for this in Wallaby so the end user doesn't have to care about these things. My initial thinking is that we can set up a monitor or a link to the calling process when it checks out a wallaby session. Then when we detect a `DOWN` signal from the process we can clean up the session ourselves. We'll also need to handle the case where we get a down signal but the user has manually checked in the process.

**Comment by brandonparsons** [comment]
I'm getting some strange behavior /w Wallaby and PhantomJS, and wondering if it is related to this issue.

After running my tests (even if I've excluded all feature tests), I see the following output in the console:

```
Finished in 0.1 seconds
1 test, 0 failures

Randomized with seed 100114
/bin/sh: line 10:  4732 Killed: 9               "$@"    <---------- This only shows up after Wallaby installed
```

And then after the test suite has exited, I end up with a pile of phantomJS processes still running:

```
$ ps aux ....

brandon           5047   0.0  0.3  3674612  43052   ??  S    11:16AM   0:19.34 /Users/brandon/.nvm/versions/node/v6.9.1/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --webdriver=49414 --local-storage-path=/var/folders/4h/4f2vml1952g4brhb9f9y65wr0000gn/T/tva1ml
brandon           5046   0.0  0.3  3674128  43636   ??  S    11:16AM   0:19.34 /Users/brandon/.nvm/versions/node/v6.9.1/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --webdriver=49412 --local-storage-path=/var/folders/4h/4f2vml1952g4brhb9f9y65wr0000gn/T/1l1hl82
brandon           5044   0.0  0.3  3677684  43364   ??  S    11:16AM   0:19.30 /Users/brandon/.nvm/versions/node/v6.9.1/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --webdriver=49416 --local-storage-path=/var/folders/4h/4f2vml1952g4brhb9f9y65wr0000gn/T/1k05fkk
brandon           5045   0.0  0.3  3675660  43648   ??  U    11:16AM   0:19.31 /Users/brandon/.nvm/versions/node/v6.9.1/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --webdriver=49409 --local-storage-path=/var/folders/4h/4f2vml1952g4brhb9f9y65wr0000gn/T/a8txx8
brandon           5043   0.0  0.3  3675676  44048   ??  S    11:16AM   0:19.31 /Users/brandon/.nvm/versions/node/v6.9.1/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --webdriver=49411 --local-storage-path=/var/folders/4h/4f2vml1952g4brhb9f9y65wr0000gn/T/1atb2sx
brandon           5042   0.0  0.3  3674612  43920   ??  U    11:16AM   0:19.31 /Users/brandon/.nvm/versions/node/v6.9.1/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --webdriver=49415 --local-storage-path=/var/folders/4h/4f2vml1952g4brhb9f9y65wr0000gn/T/1ghbgxd
brandon           5041   0.0  0.3  3675636  43636   ??  S    11:16AM   0:19.35 /Users/brandon/.nvm/versions/node/v6.9.1/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --webdriver=49413 --local-storage-path=/var/folders/4h/4f2vml1952g4brhb9f9y65wr0000gn/T/hrfuh8
brandon           5040   0.0  0.3  3676160  44132   ??  S    11:16AM   0:19.33 /Users/brandon/.nvm/versions/node/v6.9.1/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs --webdriver=49410 --local-storage-path=/var/folders/4h/4f2vml1952g4brhb9f9y65wr0000gn/T/n3svmz
```

Every time my tests run, these processes multiply, until my computer dies. I have to run a `killall phantomjs` to make this all work out.

I've tried throwing this into my feature case (as per above):

```elixir
  # https://github.com/keathley/wallaby/issues/174
  setup %{session: session} do
    on_exit fn ->
      Wallaby.end_session(session)
    end
  end
```

But this doesn't seem to help. Any hints?

**Comment by keathley** [comment]
@brandonparsons was this happening using master? Or the most recent release? Did the version of phantom change when you installed it through `brew`?

**Comment by brandonparsons** [comment]
@keathley I was using the most recent release of wallaby (not master).

To be honest I'm not sure if the version of phantomjs changed. I could have a peek when I'm back on that computer and check if it helps.

**Comment by keathley** [comment]
Closing sessions automatically when tests end has been merged and released.
