### ISSUE TITLE
Add Changelog.md ?

### ISSUE THREAD

**Issue by PragTob** [keathley/wallaby#179]
Right now changelogs are documented over on [releases](https://github.com/keathley/wallaby/releases) - I like to have a Changelog.md in the repo/code because:

* it''s the most common place for me too look for it
* it enables us to keep a running change log for things that are important and we don't have to get it all from memory and `git log` once we release
* we can just copy it over to releases once a new version is released
* Changelog can be discussed as part of the PR that does a release

If we go for a Changelog, I'd just start with 0.17.0 and would say that "for older versions refer to /releases"

What do you think? :)

**Comment by keathley** [comment]
I'm definitely for this.
