### ISSUE TITLE
Stale Reference

### ISSUE THREAD

**Issue by graeme-defty** [keathley/wallaby#207]
I am getting  stale reference trying to click a link. This has to be something I am doing wrong, otherwise the whole world would be shouting about it, but I am at a loss to know what it is. My screenshot clearly shows the link is there.

Any suggestions?
_____________
```
  def init_db(session) do
      session
      |> visit("/system/init")
      |> find(Query.text("ok"))
      |> visit("/")
      |> take_screenshot
      |> click(Query.link("Log in"))
      |> take_screenshot
  end
```
gives
```
       (wallaby) lib/wallaby/query/error_message.ex:9: Wallaby.Query.ErrorMessage.message(%Wallaby.Query{conditions: [count: 1, text: nil, visible: true], html_validation: :bad_label, method: :link, result: [], selector: "Log in"}, :stale_reference_error)
       (wallaby) lib/wallaby/browser.ex:793: Wallaby.Browser.find/2
       (wallaby) lib/wallaby/browser.ex:750: Wallaby.Browser.find/3
       test/test_helper.exs:46: RTTest.Util.init_db/1
       test/reg_test.exs:28: (test)
```

**Comment by PragTob** [comment]
Hey,

I'm not too sure but what might be hitting you there is that `find` doesn't return the session but rather the element it found. When `visit` is called with that as an argument I don't know what exactly happens but we should probably forbid it :D It might be that the error only really pops when you reach `click`.

If I'm right getting rid off `|> find(Query.text("ok"))` should fix it.

To not just get rid off it you could use `assert_has` from master or do it in a separate method you define that returns the original session again.

Does that make sense? :)

**Comment by graeme-defty** [comment]
No, you are spot on. As soon as I took that line out all is well and
working beautifully. (Perhaps a check in these functions to ensure correct
parameters would be a good idea ;-) )

Thanks for the super-rapid response.

Cheers,

Graeme

**Comment by PragTob** [comment]
It's already fixed on master as I just noticed :)
