### ISSUE TITLE
Add example of running multiple clients in a single test to the README

### ISSUE THREAD

**Issue by keathley** [keathley/wallaby#208]
I was encouraged to do this by some folks on the elixir slack. They couldn't find it in the docs and thought that it would make sense to include on the README since its a useful feature.

**Comment by PragTob** [comment]
Big :+1: from me, I think the README should include all major features or at least links to them - it results in big-ish README's but it's a nice entry point for people looking for something and evaluating the library

**Comment by keathley** [comment]
This has been added to the README.
