### ISSUE TITLE
Chrome headless driver

### ISSUE THREAD

**Issue by jb-san** [keathley/wallaby#211]
it would be great to have an option to use the 
https://developers.google.com/web/updates/2017/04/headless-chrome
as a driver

**Comment by keathley** [comment]
Thanks @jb-san. This is definitely in the works. A lot of the preliminary work is being done with #198.

**Comment by PragTob** [comment]
Heyho, reopening so other PRs can reference this and we can really close it once the driver is implemented and done - which might be a while but as @keathley said #198 already takes us almost there :)

**Comment by jb-san** [comment]
i saw that there is an experimental selenium driver.. and i found this https://intoli.com/blog/running-selenium-with-headless-chrome/ i might give it a try

**Comment by PragTob** [comment]
Just fyi, [this is happening y'all](https://twitter.com/chriskeathley?lang=en) :zap: :zap: :tada: 

![selection_076](https://user-images.githubusercontent.com/606517/26928257-bf00c16c-4c55-11e7-8821-c21b459b756b.png)

**Comment by vanderhoop** [comment]
OH YEAHHHHHHHHHHHHH!

**Comment by vanderhoop** [comment]
OH FUCK YEAHHHHHHH!
