### ISSUE TITLE
Add an option to Query to select one from a list of results

### ISSUE THREAD

**Issue by graeme-defty** [keathley/wallaby#216]
Example: On a screen with a long list of items, it is not unusual to have a `Go Back` link at the top and bottom of the list. I can easily specify that there are 2 of them, but picking one out for action a little more troublesome. Possible, certainly, but requires a bit of coding.

Suggestion: It would be nice if `Query` allowed me to select one of them to click - e.g. `pick: 1` to select the first. This could be useful in other cases where `Query` would otherwise return a list of elements but we want to select out one of them.

**Comment by PragTob** [comment]
Not sure if that's a case for a method in `Query` - couldn't something like this be done with the css [`:first-child`](https://www.w3schools.com/cssref/sel_firstchild.asp) selector or similar things?

**Comment by keathley** [comment]
The only issue with doing it in css is that it wouldn't work with the queries for form elements. In that case we'd need something like a `pick` option. A potential problem I see with `pick` is that it could potentially be non-deterministic. We'd have to make sure that the list of elements is always returned in the same order for each driver.

**Comment by graeme-defty** [comment]
That's a good point. I had not thought about the order of elements in the list. Or rather I had just assumed they would be in the order they appear in the DOM.

After a bit of a search of the W3C WebDriver spec, I arrived at the following statement:

**"If the order of elements matter, they must be sorted in shadow-including tree order, unless otherwise specified."**

There is also a definition of shadow-including tree order, but it is basically depth-first preorder.

Setting aside the fact that it should be "matters" and not "matter" :-) it appears that the result from the server-side is deterministic. Perhaps it needs to be a guideline for drivers that this order not be changed.

**Comment by keathley** [comment]
We'll also need to make sure that the drivers actually conform to the spec correctly. These are browsers that we're dealing with after all ;)

It seems like this could be a useful feature but I'd like to take a look at the implementation first. It seems like you could just do something like this: `find(session, button("Button", count: 2)) |> Enum.at(0)` That example isn't chainable but you could do something similar in the callback and allow the `find` to chain correctly.

**Comment by graeme-defty** [comment]
Yes, it is certainly possible to pick out the element you want from the list using code. I was just looking for a declarative way of doing it.

Would you like me to look at a possible implementation?

**Comment by keathley** [comment]
That would be great. I agree that having a declarative api for this situation could be really useful.

**Comment by graeme-defty** [comment]
New PR provided - #249
