### ISSUE TITLE
Fix zombie phantomjs processes

### ISSUE THREAD

**Issue by aaronrenner** [keathley/wallaby#224]
It looks like since #193 was merged, wallaby is not closing phantomjs processes after the BEAM terminates. I think a better solution (that still keeps wallaby compatible with escripts) would be to write a startup script out to /tmp and then execute it. That should prevent us having to use sub-shells which is causing these zombie proceses. I'm definitely open to other ideas if you have them.

**Comment by keathley** [comment]
Lets try the tmp file for now. I spiked on this at one point and was having some issues with the permissions but you might be able to get something working.

**Comment by vnegrisolo** [comment]
@aaronrenner are you using **mac**? I had the same problem as you described and I fixed the same way as described by @brandonparsons [here](https://github.com/keathley/wallaby/issues/174#issuecomment-292799214).

I don't know the reason but I reinstalled `phantomjs` with brew and I don't have zombie phantomjs processes anymore 💯 

```shell
npm uninstall -g phantomjs-prebuilt
npm uninstall -g phantomjs
brew install phantomjs
```

**Comment by jameslong** [comment]
As a Ubuntu 16.04 user with phantomjs-prebuilt 2.1.1 and Wallaby 0.17 I am seeing this issue. Sorry I don't have time to address this myself but it would be great to have a fix.

**Comment by keathley** [comment]
@aaronrenner Check out some of the changes I'm making to `run_command.sh` in my chromedriver branch. We may be able to resolve these issues that way.

**Comment by jeroenhouben** [comment]
Why was this issue closed? I'm still seeing phantomjs processes. And the list grows when I run the tests multiple times.

I'm on OSX high sierra, installed phantomjs through homebrew

**Comment by aaronrenner** [comment]
It should be fixed in 0.19.2. Are you still seeing the issue with the latest release?

**Comment by jeroenhouben** [comment]
Yes I have `0.19.2` in my mix.lock

**Comment by aaronrenner** [comment]
@jeroenhouben I just tested on OSX 10.11.6 using phantomjs installed through homebrew and didn't see any zombie processes left behind. I'm upgrading my wife's computer to High Sierra to see if I can recreate the issue.

**Comment by jeroenhouben** [comment]
ok thanks for investigating! should i upload a anigif or st of my "situation" would that help?

i see lots of phantoms booting, than tests run, then mosts phantoms disappear except for 2 or 3. repeating this i can see the number of phantomjs processes grow larger and larger

**Comment by aaronrenner** [comment]
Yeah, that would be helpful. The more info you can provide, the better. I'll reopen this issue.

**Comment by jeroenhouben** [comment]
FYI This a project generated with `mix phx.new --umbrella`

**Comment by aaronrenner** [comment]
@jeroenhouben Would it be possible to make a sample project that illustrates the same issue? I just ran `mix test` and `WALLABY_DRIVER=phantom mix test` (for the integration tests) on OS X 10.13.1 with Erlang 20.1 and Elixir 1.5.2 and did not see the issue.

**Comment by aaronrenner** [comment]
@jeroenhouben I've created a sample project and can recreate the issue you're seeing. I'll look into it.

**Comment by jeroenhouben** [comment]
Thanks @aaronrenner that is awesome.
