### ISSUE TITLE
All selenium tests failing with :econnrefused

### ISSUE THREAD

**Issue by graeme-defty** [keathley/wallaby#227]
All my selenium tests are failing
```
148) test local storage is not shared between sessions (Wallaby.Integration.Browser.LocalStorageTest)
     integration_test/cases/browser/local_storage_test.exs:11
     ** (MatchError) no match of right hand side value: {:error, %HTTPoison.Error{id: nil, reason: :econnrefused}}
     stacktrace:
       integration_test/cases/browser/local_storage_test.exs:13: (test)
```

Do I need some additional setup ?

**Comment by keathley** [comment]
Do you also have geckodriver installed?

**Comment by keathley** [comment]
If that doesn't solve it @aaronrenner might have some more insight.

**Comment by graeme-defty** [comment]
Someone mention "missing setup"? 

Thank you @keathley. However, now I get `{"error", "unknown command"}`:

```  1) test all/2 returns all of the elements matching the query (Wallaby.Integration.Browser.AllTest)
     integration_test/cases/browser/all_test.exs:11
     ** (FunctionClauseError) no function clause matching in Wallaby.Experimental.Selenium.WebdriverClient.cast_as_element/2
     stacktrace:
       (wallaby) lib/wallaby/experimental/selenium/webdriver_client.ex:383: Wallaby.Experimental.Selenium.WebdriverClient.cast_as_element(%Wallaby.Session{driver: Wallaby.Experimental.Selenium, id: nil, screenshots: [], server: :none, session_url: "http://localhost:4444/wd/hub/session/", url: "http://localhost:4444/wd/hub/session/"}, {"error", "unknown command"})
       (elixir) lib/enum.ex:1233: anonymous fn/3 in Enum.map/2
       (stdlib) lists.erl:1263: :lists.foldl/3
       (elixir) lib/enum.ex:1772: Enum.map/2
       (wallaby) lib/wallaby/experimental/selenium/webdriver_client.ex:34: Wallaby.Experimental.Selenium.WebdriverClient.find_elements/2
       (wallaby) lib/wallaby/browser.ex:1031: anonymous fn/3 in Wallaby.Browser.execute_query/2
       (wallaby) lib/wallaby/browser.ex:142: Wallaby.Browser.retry/2
       (wallaby) lib/wallaby/browser.ex:585: Wallaby.Browser.find/2
       integration_test/cases/browser/all_test.exs:13: (test)
```
I thought perhaps related to the version of GeckoDriver, but I am running the latest - 16.1.

Any thoughts, @aaronrenner?

**Comment by aaronrenner** [comment]
If you're on a Mac, the easiest thing to do is install the latest firefox, then

```
brew install selenium-server-standalone geckodriver 
```
then run selenium with the following command (no need to start geckodriver directly)

```
selenium-server
```

That should get you up and running with Selenium 3.4.0 and Geckodriver 0.16.1. Then you can run the wallaby integration tests against selenium in a separate terminal with

```
WALLABY_DRIVER=selenium mix test
```

If you're on linux, check out `test/tools/start_webdriver.sh` for what we do on TravisCI. The steps are different for getting selenium 2 and selenium 3 set up

@keathley, Do you want me to document this setup in the contributing section of the README? I was thinking since the selenium support is still experimental, I wasn't going to call attention to it.

**Comment by PragTob** [comment]
@aaronrenner please most definitely! When new contributors wanna get on board I want them to have a clear path to a good and functioning test setup so they don't run into these errors when they execute `mix test.all` - I also just noticed that I don't know how to run a single integration test but that's for another issue I think :)

**Comment by aaronrenner** [comment]
I'll work on documenting it. To run a single integration test, it works like the regular mix test command:

```
WALLABY_DRIVER=selenium mix test integration_test/cases/browser/visible_test.exs
```
or
```
WALLABY_DRIVER=selenium mix test integration_test/cases/browser/visible_test.exs:37
```

**Comment by PragTob** [comment]
@aaronrenner thanks! We might wanna work on a better error message then though, as without the set driver it fails with a nasty compilation error:

```
mix test integration_test/cases/browser/visible_test.exs
Compiling 6 files (.ex)
Excluding tags: [pending: true]

** (CompileError) integration_test/cases/browser/visible_test.exs:2: module Wallaby.Integration.SessionCase is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    integration_test/cases/browser/visible_test.exs:2: Wallaby.Integration.Browser.VisibleTest (module)
    (elixir) lib/code.ex:370: Code.require_file/2
```

**Comment by keathley** [comment]
I've added more details to the README that explain how to setup the other drivers. Going to close this for now.
