### ISSUE TITLE
`Wallaby.DSL.Navigation` does not exist

### ISSUE THREAD

**Issue by sevenseacat** [keathley/wallaby#23]
Mentioned in README:

```
Wallaby.DSL.Navigation.visit(session, Phoenix.Ecto.SQL.Sandbox.path_for(YourApp.Repo, self()))
```

Should be either `Wallaby.Driver.visit` or `Wallaby.Session.visit`? (they're the only two `visit` methods present)

**Comment by keathley** [comment]
Good catch! That was copied over from a previous version of the api. It should be `Wallaby.Session.visit`
