### ISSUE TITLE
`Wallaby.Browser.current_path/1` doesn't include query parameters

### ISSUE THREAD

**Issue by scmx** [keathley/wallaby#241]
Hello, I noticed that `current_path(session)` will give the current path without query parameters. For my use case I wanted to test against a path with query parameters included.
```elixir
assert current_path(session) == "/login/?target=%2Fusers"
```
Looking at https://github.com/keathley/wallaby/blob/master/lib/wallaby/phantom/driver.ex#L171-L178 we can see this implementation:
```elixir
  def current_path!(session) do
    check_logs! session, fn ->
      session
      |> current_url!
      |> URI.parse
      |> Map.get(:path)
    end
  end
```

Would you like a pull-request that changes it to return query parameters as well?

EDIT: And same for https://github.com/keathley/wallaby/blob/master/lib/wallaby/experimental/selenium/webdriver_client.ex#L127-L136

**Comment by scmx** [comment]
I've solved by use case for now with:
```elixir
assert current_path_with_query(session) == "/login/?target=%2Fusers"
```
```elixir
defmodule MyApp.Web.WallabyHelpers do
  @moduledoc """
  WallabyHelpers are extensions to `Wallaby.DSL` needed for browser tests.
  """

  use Wallaby.DSL

  @doc """
  current_path_with_query takes `Wallaby.Browser.current_url/1`, strips away the
  hostname to only keep the path, while also making sure that there is always a
  trailing slash because route helpers will generate urls with trailing slashes
  when query parameters are specified.

  Wallaby has a `Wallaby.Browser.current_path/1`, but the problem with it is
  that it doesn't include query parameters.
  """
  def current_path_with_query(session) do
    session
    |> current_url
    |> String.split("/")
    |> Enum.slice(3..-1)
    |> Enum.map(&"/#{&1}")
    |> Enum.join("")
    |> URI.parse
    |> put_trailing_slash
    |> URI.to_string
  end

  defp put_trailing_slash(%URI{path: path} = uri) do
    if String.ends_with?(path, "/") do
      uri
    else
      %{uri | path: path <> "/"}
    end
  end
end
```

```
defmodule MyApp.Web.FeatureCase do
  using do
    quote do
      ...
      import MyApp.Web.WallabyHelpers
    end
  end
end
```

**Comment by keathley** [comment]
Thanks for this @scmx :+1:

I think if we want to provide additional functionality here then the best thing would be a helper like `current_params`. That makes the most sense to me since the params aren't _technically_ part of the url path.

**Comment by PragTob** [comment]
:+1: to what @keathley said :)

**Comment by keathley** [comment]
I'm going to close this for now. If anyone wants to provide a PR for `current_params` I would love to take a look at it.
