### ISSUE TITLE
Nicer API for execute_script with callback?

### ISSUE THREAD

**Issue by opsb** [keathley/wallaby#254]
I've started using this helper to avoid having to do the assert_receive dance. Is it worth using this approach for `execute_script(session, script, callback)`?

```
  def execute_script_with_callback(session, script, callback) do
    assertion_id = Ecto.UUID.generate

    execute_script(session, script, fn value ->
      send self(), {assertion_id, value}
    end)

    receive do
      {^assertion_id, actual_value} -> callback.(actual_value)
    after
      500 -> flunk("timed out waiting for script")
    end

    session
  end
```

example use

```
    execute_script_with_callback(
      session,
      "return window.localStorage['foo']",
      fn actual_value ->
        assert "bar" == actual_value
      end
    )
```

**Comment by keathley** [comment]
That looks totally reasonable to me although I'm actually surprised we have to do this. `execute_script` shouldn't be async. Is the issue that it can time out? 

Sorry I'm probably being dense but I'm just trying to understand the root issue 😄 .

**Comment by opsb** [comment]
I have to admit I only gave https://github.com/keathley/wallaby/pull/183 a cursory look originally. Now I reread it I don't actually see what the issue is 😕 . @krankin could you expand on what the issue is here?

**Comment by krankin** [comment]
@opsb -- I may not fully understand what you're asking. The reason #183 has tests using ```assert_receive``` calls is to allow the tests to confirm the callback passed to ```execute_script``` is being executed. The wrapper around it is a good idea IMO, especially if you want to check for timeouts and the like. You can use ```execute_script``` without the ```assert_receive```, but if you put any assertions in the callbacks you may get false positives if a situation arises that your callback isn't executed.

**Comment by krankin** [comment]
It's also entirely possible there's a better way to ensure the callback is called.

**Comment by keathley** [comment]
When would the callback not be called?

**Comment by opsb** [comment]
hmm, I'm not sure happened when I was looking at this earlier but I was finding that the callback wasn't being called. Now I've checked it again and it works as expected, without the assert_receive, guess I had a gremlin in there... @krankin I see your point, without the assert_receive it's possible that execute_script might have a broken implementation(where the callback isn't called) and you'd still get green.
