### ISSUE TITLE
Set up linting

### ISSUE THREAD

**Issue by PragTob** [keathley/wallaby#255]
We should really set up linting e.g. [credo](https://github.com/rrrene/credo/) with some sensible configuration for the project.

I believe it makes contributions easier as contributors don't have to fix style problems, which also makes reviews easier and also it makes the whole database more consistent.

**Comment by aaronrenner** [comment]
I completely agree linting would be awesome. It will just take quite a bit of work to fix all of the style issues in the codebase. I wonder if there's a way to ease into using credo without failing all of our builds until we fix all of the style issue? I know https://www.houndci.com takes the approach of only reviewing pull requests so you don't have to update the entire app at once. I wonder if https://ebertapp.io has a similar approach.

**Comment by PragTob** [comment]
ha, good point we could use ebert!

But even without it, you can configure credo with todos so that you already enable a couple of rules and put the others into TODO basically and work on them PR by PR. We did that in one of our projects and it works quite well. Builds absolutely shouldn't be failing :)
