### ISSUE TITLE
Wallaby.Query.text_field - label text is an 'include' query. Fails with 2 fields with same string

### ISSUE THREAD

**Issue by jeffdeville** [keathley/wallaby#256]
My registration form has Password, and Password confirmation.

`fill_in(text_field("Password confirmation"), with: "password")`

works just fine.  However:

`fill_in(text_field("Password"), with: "password")`

fails because it finds 2 elements.  This happens because the generated XPath is doing a text include query.  I can certainly see why such a decision was made, but I think it might be better to bracket that regex in ^\s+ and \s+$.

Will submit a PR.

**Comment by keathley** [comment]
This is related to #306 and #344 so I'm going to close this and continue the discussion there.
