### ISSUE TITLE
end-to-end testing a basic form using reCaptcha v2

### ISSUE THREAD

**Issue by jacobw56** [keathley/wallaby#258]
First, thanks for the awesome job on wallaby.  It is such a useful tool!

This is more of a documentation request if there is someone smart enough to figure it out (so far, not me).  I'd like to be able to run an end to end test on a simple test page containing reCaptcha v2, but I can't get it to even show up properly in either phantom or selenium, let alone find the element to manipulate.  If you know how to accomplish this (it seems non-trivial) it would be nice to have the example documented.

**Comment by keathley** [comment]
A quick google search turned this up: https://developers.google.com/recaptcha/docs/faq#id-like-to-run-automated-tests-with-recaptcha-v2-what-should-i-do.

Looks like you'll need to set those keys when running tests.

If the library isn't loading at all then it might be an issue with loading the assets from an external source in phantom and selenium. Being able to see your html and a basic test would help in diagnosing as well.

**Comment by keathley** [comment]
@jacobw56 I'm going to close this for now. If you have other issues feel free to re-open.
