### ISSUE TITLE
Usage question: should we rebind session after each query?

### ISSUE THREAD

**Issue by jameslong** [keathley/wallaby#263]
Currently, our tests pass even without rebinding session e.g.

```
test "some test", %{session: session} do
  login(session, "test@example.com", "example_password")
  assert(has_text?(session, "Login text"))
end
```

However, this is counterintuitive: each query function returns a new session struct so you would assume that session needs to be rebound. e.g.

```
test "some test", %{session: session} do
  session = login(session, "test@example.com", "example_password")
  assert(has_text?(session, "Login text"))
end
```

My question is, going forward can we rely on our tests working without the rebinding? i.e. will the session struct continue to be a simple proxy to the driver process?

And if so, is it the case that the only reason the query functions return a session struct is to allow chaining?

**Comment by keathley** [comment]
The session is very rarely changed. I believe the only time we'll return a new session struct is after a screenshot (we add the path to each screenshot to the `screenshots:` list on the session struct).

Currently the only reason to return the session struct is to allow chaining. Its been suggested before that we should hide that session from the tests all-together. I haven't been convinced by those arguments yet but its not out of the question that we would do that in the future.

Does that help @jameslong?

**Comment by jameslong** [comment]
@keathley Thanks. Just to clarify, the recommendation is not to rebind session for now?
