### ISSUE TITLE
It would be nice to pretty-print a `Wallaby.Element`

### ISSUE THREAD

**Issue by knewter** [keathley/wallaby#266]
Right now I can do this if I pipe it and get the `outerHTML`:

```elixir
some_element
|> Element.attr("outerHTML")
```

but it's not so pretty :) Would be neat to get a nice output of "what exactly did I grab here?" for debugging purposes. Only added this issue because @PragTob suggested it, otherwise I'd feel like I was piling on personal wishlist features :)

**Comment by nathanl** [comment]
This issue helped me a lot with debugging.

I had a test with `assert_has(css("some_selector"))` that was failing, and I wanted to figure out why.

I tried using `take_screenshot/1` to see the page, but it appeared that the element I wanted had been rendered.

I tried using `page_source/2` to see the HTML, but that showed me the page before JavaScript did any DOM manipulation, and I was looking for something it would create.

Finally, I stumbled on this issue and figured out I could see the DOM as modified by JavaScript by using:

```elixir
File.write("/tmp/the_page.html", Element.attr(find(session, css("body")), "outerHTML"))
```
Inspecting that output showed me what I was asserting incorrectly.

I'm going to hang on to this trick, but it might be nice to have a more straightforward way to inspect the current DOM.

**Comment by keathley** [comment]
One solution for this would be to use the inspect protocol. I'm not sure how I feel about having side-effects in there or if the results would end up being surprising to folks. Otherwise we could have something like `Element.inspect/1`. What do y'all think?

**Comment by PragTob** [comment]
Definitely no side effects in the inspect protocol please. A separate function to inspect elements is highly preferred to my mind :)

**Comment by johnmosesman** [comment]
@keathley Not sure if this fits within `take_screenshot/1` or not, but it would be great to have an option to save the output as an HTML file. The image works well for visually seeing if the elements are there, but there are many times when I want to inspect the HTML structure.

**Comment by PragTob** [comment]
@johnmosesman I think it should be a different function call, like `dump_html` or whatever. I have a helper function somewhere to at least print it for myself :)

**Comment by nathanl** [comment]
I've added this to my `FeatureCase`:

```elixir
using do
  quote do
    use Wallaby.DSL

    alias Mealthy.Repo
    import Ecto
    import Ecto.Changeset
    import Ecto.Query

    import Mealthy.Factory
    import Mealthy.Web.Router.Helpers

    def dump_html_to(session, filename) do
      File.write(
        filename,
        Wallaby.Element.attr(
          find(session, Wallaby.Query.css("html")),
          "outerHTML"
        )
      )
      session
    end
  end
end
```

I use it like:

```elixir
session
    |> dump_html_to("/tmp/awesome.html")
    |> assert_has(css("h1", text: "Something Awesome"))
```

**Comment by zedtux** [comment]
@keathley That would be great to have both the HTML and image screenshot on error so that debugging is easier.

**Comment by mhanberg** [comment]
I'm going to take a look at this. Was there a direction that was settled on? I feel like the `Element.inspect` path is a solid choice.

**Comment by keathley** [comment]
Lets start there and get the functionality working. We can always update the name later if need be.
