### ISSUE TITLE
fill_in doesn't work when a input is hidden is this intended?

### ISSUE THREAD

**Issue by ahmetabdi** [keathley/wallaby#267]
If it is intended is there a way to populate the hidden field?

`<input id="table_column_id" name="table[column_id]" type="hidden">`

`fill_in(session, css("#table_column_id"), with: column.id)`

Error:

`** (Wallaby.QueryError) Expected to find 1, visible element that matched the css '#table_column_id' but 0, visible elements were found.`

**Comment by PragTob** [comment]
It is intended for hidden inputs not to be found, that's also why the error message says "visible element". You can check out the [Query Options](https://hexdocs.pm/wallaby/0.16.1/Wallaby.Query.html#module-query-options) - you can pass in `visible: false` to your query (`css`) and then it should work.
