### ISSUE TITLE
Wallaby does not close Chrome after tests - using Selenium

### ISSUE THREAD

**Issue by viniciussbs** [keathley/wallaby#269]
I'm using Chrome with Selenium and Wallaby does not close the browsers after the tests finish running.

I have `selenium-server` running and I start my test suit with `WALLABY_DRIVER=selenium mix test`.

This is how I start sessions: 

```elixir
{:ok, session} = Wallaby.start_session(
  driver: Wallaby.Experimental.Selenium,
  capabilities: %{browserName: "chrome"}
)
```

I've tried to call `Wallaby.end_session(opts)` on `on_exit` but ended up facing DB ownership issues.

**Comment by keathley** [comment]
This isn't fixed for selenium or phantom yet but if you use the chrome driver: https://github.com/keathley/wallaby#drivers this should be fixed.

You get db connection issues when an internal process has access to your db connection still. This can sometimes be remedied by forcing the browser to block until those processes have closed.

**Comment by sabondano** [comment]
@keathley you mentioned above that you can sometimes remedy the db connection issues by forcing the browser to block until those processes have closed. Is there a way for Wallaby users to do this?
