### ISSUE TITLE
Can't visit "about:blank" when using base URL

### ISSUE THREAD

**Issue by viniciussbs** [keathley/wallaby#270]
I'm using base URL. When I visit "about:blank", Wallaby appends it to the base URL.

**Comment by keathley** [comment]
To make this work we would have to provide a conditional case to the `visit` logic that checked to see if you were trying to navigate to "about:blank" and not prepend the base url in that case. I'm not sure that this is a common enough use case to warrant adding that kind of logic. Can you talk a little bit about your use case for this?

**Comment by viniciussbs** [comment]
When people connect to my site they connect to a channel and they loose connection on exit. I have a logic running on channel terminate event. That's what is happening:

- Wallaby starts a new session
- test runs
- Wallaby ends the session
- logic on channel's terminate event starts running
- I get a DB ownership error

To handle this situation, I need to simulate people disconnecting my site so channel's terminate logic can finish running before the end of the test.

Today I'm handling logging user out, but I'm afraid I'll have to connect any user to the websocket channel.

Since this is a corner case, we can close the issue.

**Comment by keathley** [comment]
I see. Thanks for the explanation. I think you might be able to get around this by having your "user" visit your sites 404 page. It'll depend on how you've set up your channel connection stuff but that might work. If you find a good pattern for this feel free to post it here. Dealing with db connection issues can be tricky and it would probably be worth writing about some different solutions.
