### ISSUE TITLE
Handle alerts in chrome

### ISSUE THREAD

**Issue by keathley** [keathley/wallaby#277]
We need to support the same alert functionality that we use for phantomjs in chrome.

**Comment by tk8817** [comment]
@florinpatrascu - feel like picking this up for fun? we handle this gracefully in `watir` http://watir.github.io/docs/javascript-dialogs/

**Comment by keathley** [comment]
We had to build an api for making this work in phantom. It should be much easier with chrome.

**Comment by florinpatrascu** [comment]
trying to get my head wrapped around this :)

**Comment by keathley** [comment]
@florinpatrascu awesome thanks! If you have specific questions feel free to ask them here or on the elixir slack/irc. I'm `keathley` on both.

**Comment by florinpatrascu** [comment]
I am quite new to this, learning to deal with the chromedriver (in Elixir/Wallaby). My team here is using it in heavy-duty mode for many projects (Ruby/Watir), but we also have newer projects where we're starting to use Wallaby :)

**Comment by keathley** [comment]
Oh rad! Just let me know if I can help in any way.

**Comment by keathley** [comment]
Closing this now that #285 has been merged.
