### ISSUE TITLE
Capture JS logs in chrome

### ISSUE THREAD

**Issue by keathley** [keathley/wallaby#278]
It would be good to capture js errors and logs in chromedriver the same way that we do for phantom. I believe we should be able to do this from the chromedriver verbose logs. If not then we'll have to find a way to capture them somehow.

**Comment by VEkh** [comment]
+1 👍

**Comment by QwertyJack** [comment]
I wonder how to hide JS log for phantomjs.

**Comment by keathley** [comment]
@QwertyJack You can change your config: https://github.com/keathley/wallaby#javascript-logging-and-errors

**Comment by QwertyJack** [comment]
Get it, thx.
