### ISSUE TITLE
Publishing automation

### ISSUE THREAD

**Issue by keathley** [keathley/wallaby#289]
What do y'all think about using something like https://github.com/wojtekmach/shipit for publishing new versions of wallaby? Anyone used it before?

**Comment by PragTob** [comment]
Hm, didn't use it before. From what I can see it adds some checks and some git automation. Not sure if it's worth the overhead although doing the tag creation etc. manually always seems a bit error prone.

**Comment by keathley** [comment]
Yeah automating a lot of this seems really nice. Just not sure if we couldn't do it as a shell script or something similar.

**Comment by keathley** [comment]
I'm going to close this for now. If this is something that we want then we can write a few shell scripts to make it happen.
