### ISSUE TITLE
Potential for confusion with wallaby.js

### ISSUE THREAD

**Issue by AndrewIngram** [keathley/wallaby#29]
Wallaby.js is a test runner for JavaScript that's been around for a while (relatively speaking), there's big potential for confusion here.

http://wallabyjs.com/

**Comment by keathley** [comment]
Thanks @AndrewIngram. I'd never heard of WallabyJS before this. I'm not opposed to changing the name if people have other suggestions. Originally I choose Wallaby because it followed the same theme as Capybara. I guess I should have done some extra research.

**Comment by tokafish** [comment]
Personally, I don't think it's confusing - one tool is for Elixir, and one is for javascript. Happy to acknowledge the existence of Wallaby.js on our homepage/docs if we ever get that far :)
