### ISSUE TITLE
Input box filled wrongly

### ISSUE THREAD

**Issue by QwertyJack** [keathley/wallaby#292]
`fill_in(text_field("User"), with: "123456")` may fill User with '12456', especially with a long text.

**Comment by keathley** [comment]
@QwertyJack can you give me an example of long text that isn't working? Does this happen for all text input fields? Is there any javascript involved? What browser are you using?

**Comment by keathley** [comment]
@QwertyJack Just wanted to see if you were still having issue with this.

**Comment by QwertyJack** [comment]
I think the js is so heavy that input is filled with error text.
