### ISSUE TITLE
Chrome driver won't take screenshot when failure

### ISSUE THREAD

**Issue by QwertyJack** [keathley/wallaby#293]
When using chrome driver, wallaby says 'write file error' when taking screenshot after test failure.
Chrome 60, chromedriver 2.31

**Comment by keathley** [comment]
@QwertyJack what operating system are you on? Is there any other configuration options you've changed for wallaby? If you set `screenshot_dir: ` in your configuration to a specific directory do you still have this error?

**Comment by QwertyJack** [comment]
Those weird behavior comes together and the system is quite complicated so that I am not sure what's wrong with it.
I will soon build a toy model to reproduce the error, together with issue #292 .

**Comment by QwertyJack** [comment]
After upgrade pheonix to v1.3 and wallaby to 0.19 the problem disappear.
