### ISSUE TITLE
Phantomjs may fail to load some large js and css

### ISSUE THREAD

**Issue by QwertyJack** [keathley/wallaby#294]
The chrome driver works fine.

**Comment by keathley** [comment]
@QwertyJack can you give me an example of a large js / css file to work with? Phantom is working fine with our application's assets and I would count them as "large". I think the more likely scenario is you're having an issue with phantom loading files from a cdn or phantom isn't properly shimmed to handle the version of javascript that you're using. But without more information its impossible to say.

**Comment by QwertyJack** [comment]
You are right.
