### ISSUE TITLE
Fails if phantomjs is not installed globally

### ISSUE THREAD

**Issue by naps62** [keathley/wallaby#295]
I have this in my config, as specified in the docs:

```
config :wallabe, phantomjs: "./assets/node_modules/.bin/phantomjs"
```

However, the app still fails until I globally install phantomjs as well (`npm install phantomjs -g`)
Looking at the internal code, it seems that my custom path is still used, but the `Wallabe.Phantom` crashes if a global one does not exist, regardless of the configuration

Is this intended for some reason, or an oversight?

Changing this behaviour in `Wallabe.Phantom.validate()` seems to fix the issue, and my tests still work with only a local installation and not a global one, so I'd guess this is an oversight

(I'll probably open a pull request soon with a fix for this)

**Comment by keathley** [comment]
One other thing that you might need to do is change your spelling of `wallaby` from `wallabe`. Not sure if thats your issue though :smile:

**Comment by naps62** [comment]
@keathley I picked that up later on :smile: 
but no, my issue was still valid regardless of the typo
