### ISSUE TITLE
PhantomJS crashes. Error message doesn't explain much

### ISSUE THREAD

**Issue by naps62** [keathley/wallaby#297]
I just opened another issue & PR related to phantomJS, but this one is actually unrelated

Regardless of using a global phantomjs installation or a local one, I get this error:

```
  1) user can login (Utrust.UserListTest)                                       
     test/features/login_test.exs:6        
     ** (Wallaby.JSError) There was an uncaught javascript error:                      
                     
     [WDS] Disconnected!                   
       error (:0)    
                     
     code: |> visit("/")                   
     stacktrace:     
       (wallaby) lib/wallaby/phantom/logger.ex:12: Wallaby.Phantom.Logger.parse_log/1  
       (elixir) lib/enum.ex:675: Enum."-each/2-lists^foreach/1-0-"/2                   
       (elixir) lib/enum.ex:675: Enum.each/2                                           
       (wallaby) lib/wallaby/phantom/driver.ex:497: Wallaby.Phantom.Driver.check_logs!/2
       (wallaby) lib/wallaby/browser.ex:707: Wallaby.Browser.visit/2                   
       test/features/login_test.exs:8: (test)            
```

I can't really figure out what to do here.
In the meantime, switching to use headless chrome seems to work, but since support for that is only experimental, I didn't want to rely on it so much

**Comment by keathley** [comment]
Whats happening is that your page is throwing a JS error, wallaby is capturing that js error, and its failing your test. This is actually working as intended. Wallaby fails tests when it detects a JS error so that you don't accidentally ship code with errors that might cause regressions for your users. If you want to disable this you can set `js_errors: false` in your config. :+1:

**Comment by naps62** [comment]
Thanks. I actually figured that was the case, but couldn't find any reference to that `js_errors: false` option

After a quick look a the readme again I realise that it's there, and I just missed it
