### ISSUE TITLE
Suggest an execute_script that returns script value

### ISSUE THREAD

**Issue by andrewhao** [keathley/wallaby#312]
After the change in https://github.com/keathley/wallaby/pull/183, `execute_script` now returns the session instead of the script value. Accessing the script value is now done in a callback.

I have a use case where it would be nice to return the script value - @keathley may be familiar with this app :) In this app, we use page modules with nice helper functions to derive various facts about a page. Some of these helper functions use JS scripts to return values, such as measuring pixel widths and other layout properties. These values may be transformed further by the caller before they hit any test assertions.

It would be nice to have a variant of `execute_script` that returned the script value instead. Or perhaps someone could show me how to write a higher order function that would preserve this behavior using `execute_script` under the hood?

**Comment by PragTob** [comment]
:wave: and thanks for the report!

So, I fear we might have to supply a variant that does what you want some time as I can see how other people might want that. 

As for a higher order function, I fail to come up with a simple way right now :| As we can't access the return value of the callback directly we probably would have to work with processes/agents which isn't exactly ideal.

while I thought about that... might be enough to `send` the return value and then `receive` it in the higher order function.

if we did add another variant of the function, what would it be called?

**Comment by andrewhao** [comment]
Thanks for the quick reply, @PragTob!

> might be enough to send the return value and then receive it in the higher order function.

Yeah, the fix I've settled on now simply refactors our upstream calling functions to also use callbacks. It's not super ideal, but it works.

Suggest a name like `execute_script_and_return`? or perhaps `evaluate_script`, which may imply that the script is expected to return a value?

**Comment by PragTob** [comment]
I like `evaluate_script` :)

**Comment by keathley** [comment]
I'm on the fence about this. Honestly, I'm just leery about adding new functions to the api at this point :wink:. I'll try to explain a bit of my thinking and express the problem as I see it. Please tell me if I'm misrepresenting or misunderstanding any of the nuances.

Its currently possible to solve this issue using `execute_script/2` but it requires you to write code like this:

```elixir
session
|> execute_script(@two_plus_one_script, & &1 >= 3)

# The same but this time with functions!

session
|> two_plus_one(&is_three/1)

def two_plus_one(session, cb) do
  session
  |> execute_script(@two_plus_one_script, & assert cb.(&1))
end

def is_three(3), do: true
def is_three(_), do: false 
```

There are some nice properties of breaking these functions into smaller pieces and theoretically there is some re-use to be gained by this separation. But this is a very simplistic example and the cleanliness and readability (and I would assume even the maintainability) of these tests start to suffer long term.

The alternative would be something like this:

```elixir
assert session
|> eval_script(two_plus_one()) == 3
```

The only drawback in this case is just that its another function which means a little bit extra maintenance for us and something else that the user has to remember. I guess there is also a danger of a user using the incorrect version and then being surprised by the result.

I definitely see the utility in something like `evaluate_script` so I'm not opposed to its inclusion. Just as long as we don't set a precedent for having two versions of every function, one that chains and one that returns a value, I think we'll be ok :smile:. Sorry for the wall of text. Just wanted to get my thoughts out there. Lemme know what you think.

**Comment by PragTob** [comment]
:wave: 

Thanks for your thoughts! I definitely see the danger and I definitely want to avoid adding more functions that pipe and don't pipe :D 

In the case mentioned above, where the value is returned from the script and then processed further before hitting any assertion it seems to make some sense. Feels a bit peculiar to cram all of this into one callback of the `execute_script` function.

Albeit, it's definitely possible as you describe and just showed. As I said, just feels a bit weird if there is a whole bit of transformation and assertions going on to have it all in a callback rather than the main test flow.

**Comment by andrewhao** [comment]
Yeah - I talked with @keathley about this and I'm (personally) OK with keeping the current API. Perhaps there will be more feedback about this approach in the future.

**Comment by keathley** [comment]
Going to close this for now. Happy to revisit in the future.
