### ISSUE TITLE
Can I get a fuller JS stacktrace?

### ISSUE THREAD

**Issue by nathanl** [keathley/wallaby#317]
I have a test failure right now like this:

```
 ** (Wallaby.JSError) There was an uncaught javascript error:

 Unhandled promise rejection TypeError: undefined is not an object (evaluating 'data.id')
   (anonymous function) (http://localhost:4001/js/app.js:12105)
```

This doesn't tell me much. The JS line it points to is some framework code, and the error doesn't happen in dev mode.

Is it possible to get a fuller JavaScript stacktrace out of Wallaby? (I'm using the PhantomJS driver.)

**Comment by nathanl** [comment]
OK, actually this *does* happen in development, I just wasn't reproducing it correctly. 😆 Not Wallaby's fault!

**Comment by keathley** [comment]
@nathanl I'll double check this but unfortunately iirc we're returning everything we get from phantom. So its probably a limitation on phantom's side. Headless chrome might be able to return more info but its still experimental in wallaby at the moment.
