### ISSUE TITLE
Add docs for compiling phoenix assets before running tests

### ISSUE THREAD

**Issue by aaronrenner** [keathley/wallaby#330]
I just ran across [this thread](https://elixirforum.com/t/how-do-i-compile-my-javascript-assets-with-webpack-for-wallaby-feature-tests/9735) on ElixirForum where someone was trying to figure out how to compile their Phoenix assets before running their wallaby test suite. I'm not quite sure what needs to be done, but it would be nice if we provided some guidance in the README.

**Comment by keathley** [comment]
Yeah its probably a good idea to add a something to the docs. What if we add a "Phoenix Setup" section or similar and we can provide some information there. 

For our production apps we just run `brunch build` if we're testing against the UI. We considered adding a step in our `mix test` alias to build assets but we felt like it would make our test workflow too slow. I guess we can at least present some alternatives for folks.

**Comment by PragTob** [comment]
Sounds like a great idea and worthwhile improvement @keathley ! :)

**Comment by keathley** [comment]
Opened a PR for this.
