### ISSUE TITLE
How do I get through Basic Authentication?

### ISSUE THREAD

**Issue by terenceponce** [keathley/wallaby#331]
I'm new to Elixir and this is my first time trying out Wallaby.

I'm already stuck because a page that I have to test requires Basic Authentication to go through.

How do I make Wallaby fill out the form in the dialog box that appears when visiting the page for the first time? Is this possible?

**Comment by PragTob** [comment]
Huh... I'm not sure. @keathley 

Most of what we do interacts with the DOM, not sure if that functionality is there. However, if you test your own application you should be able to deactivate the basic auth for testing, shouldn't you? :)

**Comment by joshuataylor** [comment]
Can't you set the url to http://foo:bar@example.com?

**Comment by keathley** [comment]
I'm...actually not sure how to do this 🙃 .

If I remember correctly phantom requires you to pass in the auth into the settings when you start a session. We don't expose that for the session so that might be tricky. You can't directly interact with the alert because phantom doesn't let you.

If you use chromedriver then you should be able to interact with the dialog directly using `accept_prompt/3`.

**Comment by keathley** [comment]
@terenceponce were you able to work through this?

**Comment by dsdshcym** [comment]
I ran into the same issue today.

And setting `base_url` to http://foo:bar@example.com can pass the basic auth correctly.

But I'm not sure how to use `accept_prompt/3` to enter the username/password. If my understanding is correct, `accept_prompt/3` only accepts one input value, instead of two.

**Comment by keathley** [comment]
Using the URL for basic auth is the preferred method.

**Comment by lvenegas** [comment]
When testing a Phoenix application, your `test_helper.exs` file could be structured as follows:

```elixir
%URI{scheme: scheme, host: host, port: port} = YourApp.Endpoint.struct_url()

base_url = "#{scheme}://username:password@#{host}:#{port}"

Application.put_env(:wallaby, :base_url, base_url)
```
