### ISSUE TITLE
Could not compile dependency :mimerl

### ISSUE THREAD

**Issue by zedtux** [keathley/wallaby#332]
I am new to Exilir/Phoenix/Cabbage/Wallaby and I have the issue that when I add the following to my `mix.exs` file:

```exs
  defp deps do
    [
      {:phoenix, "~> 1.3.0"},
      ...
      {:cabbage, "~> 0.3.0"},
      {:wallaby, "~> 0.19.2", only: :test}
    ]
  end
```

I have the following error when I run `docker-compose exec app mix test`:

```bash
escript: exception error: no match of right hand side value undefined
  in function  rebar_log:log/3 (/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_log.erl, line 94)
  in call from rebar3:handle_error/1 (/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar3.erl, line 325)
  in call from escript:run/2 (escript.erl, line 759)
  in call from escript:start/1 (escript.erl, line 277)
  in call from init:start_em/1
  in call from init:do_boot/3
** (Mix) Could not compile dependency :mimerl, "/root/.mix/rebar3 bare compile --paths "/application/_build/test/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile mimerl", update it with "mix deps.update mimerl" or clean it with "mix deps.clean mimerl"
```

I don't know if I'm opening the issue at the right place, but as it happens to me when adding the dependency, I guess it could be interesting to have it here, but if not, feel free to guide me to the right place.

How can I fix that issue?

**Edit:** I have exactly the same issue when adding Hound so doesn't seems to be an issue with Wallaby only.

**Comment by keathley** [comment]
The root issue is that your docker container isn't possible to compile the `mimerl` package. `mimerl` is a dependency of `hackney` which is a dependency of `httpoison` which is what wallaby uses to talk to different webdrivers (and presumably hound as well). I would suspect it has something to do with your docker container or something similar.

**Comment by zedtux** [comment]
Thank you @keathley for your comment.

The `mimerl` package is install at Docker image build time, but also I did run `mix deps.get` and all packages are fine.
I have also ran `mix deps.update mimerl` as recommended in the error message, I have a positive output, but running again the `mix test` shows me the same error.

I will investigate more about it ... but when I have installed `cabble`, I didn't had any issue like this.

**Comment by zedtux** [comment]
I have solved this issue but not 100% sure which solved the problem ... What I did is described in this SO: https://stackoverflow.com/questions/47671356/could-not-compile-dependency-mimerl-when-adding-wallaby-to-my-elixir-phoenix-pr

**Comment by zedtux** [comment]
@keathley I finally figured out was what the issue with rebar3: proxy!

I have a company proxy configured on my machine and unsetting all the environment variables and the docker 4 mac proxy settings too solved my issue.

**Comment by keathley** [comment]
Glad you figured it out 👍
