### ISSUE TITLE
Random segmentation faults with headless Chrome

### ISSUE THREAD

**Issue by adamniedzielski** [keathley/wallaby#335]
Thanks for this great library, I was honestly surprised how easy it was to configure it and start using in a project 👍 👍 👍 

My setup:
- Wallaby 0.19.2
- Elixir 1.5.3
- OTP 20.1
- Chrome 63
- Chromedriver 2.31
- macOS High Sierra

I'm experiencing random segmentation faults that look like this:

```
  1) test create new user account (Multipster.SignUpTest)
     test/features/sign_up_test.exs:5
     ** (RuntimeError) Wallaby had an internal issue with HTTPoison
     code: |> fill_in(Query.text_field("Email"), with: "test@example.com")
     stacktrace:
       (wallaby) lib/wallaby/httpclient.ex:32: Wallaby.HTTPClient.make_request/4
       (wallaby) lib/wallaby/experimental/selenium/webdriver_client.ex:45: Wallaby.Experimental.Selenium.WebdriverClient.set_value/2
       (wallaby) lib/wallaby/driver/log_checker.ex:6: Wallaby.Driver.LogChecker.check_logs!/2
       (wallaby) lib/wallaby/element.ex:163: Wallaby.Element.set_value/2
       (wallaby) lib/wallaby/browser.ex:453: Wallaby.Browser.find/3
       test/features/sign_up_test.exs:8: (test)

/Users/adam/workspace/elixir/multipster/_build/test/lib/wallaby/priv/run_command.sh: line 7: 94426 Segmentation fault: 11  "$@"
/Users/adam/workspace/elixir/multipster/_build/test/lib/wallaby/priv/run_command.sh: line 8: kill: -: arguments must be process or job IDs
```

So far I couldn't identify any pattern when it happens. I'm using headless Chrome in another project from Ruby and I never had a similar problem.

**Comment by PragTob** [comment]
:wave: 

Hellooo :)

That's interesting... support is still experimental but obviously this shouldn't happen :D Not sure why this happens, seems it originates in our helper script that is supposed to shut down all the processes iirc

Do you have any other error log maybe from chromedriver itself?

Maybe @aaronrenner has an idea (he built the bulk of the chrome driver support).

Happy holidays :santa:

**Comment by drapergeek** [comment]
We're running into the same problem. It's intermittent.

I've attached the chromedriver log below. I apologize for the lengthy log but hopefully it's helpful. If I can get anything else to you, please let me know!
 
[chromedriver.log](https://github.com/keathley/wallaby/files/1587609/chromedriver.log)

**Comment by keathley** [comment]
I've seen errors like this:
```
/Users/adam/workspace/elixir/multipster/_build/test/lib/wallaby/priv/run_command.sh: line 7: 94426 Segmentation fault: 11  "$@"
/Users/adam/workspace/elixir/multipster/_build/test/lib/wallaby/priv/run_command.sh: line 8: kill: -: arguments must be process or job IDs
```

In wallaby's own test suite. Its an issue in how phantom is being managed by our shell script. I think @aaronrenner had a fix for it the last time I talked to him. I think the root of the issue is that wallaby is killing chromedriver by sending too many requests to it too quickly which can cause requests to fail. We try to account for this by retrying commands until they succeed but we probably need to add some slight backoff to relieve some of the pressure on chromedriver.

**Comment by keathley** [comment]
#377 should help solve this.
