### ISSUE TITLE
attach_file/3 doesn't set the input value in a phoenix project

### ISSUE THREAD

**Issue by marcdel** [keathley/wallaby#341]
I've been trying to test a file upload element in an existing project but it never seems to change the value of the component. I thought maybe it was some unrelated html/css/etc. interfering so I created an empty phoenix project, added wallaby, and added a single file input and a corresponding test. I've tried a bunch of different ways of calling `attach_file`, but obviously I'm still doing something wrong.

Issue reproducable here: https://github.com/marcdel/photo_uploader

The relevant bits are:

__photo_upload_test.exs__
```
test "can upload a photo 2", %{session: session} do
  session
  |> visit("/")
  |> attach_file(file_field("Photo"), path: "test/support/photo.png")
  |> take_screenshot()

  assert find(session, css("#user_photo")) |> has_value?("test/support/photo.png")
end
```

__index.html.eex__
```
<div class="col-lg-6">
  <div class="form-group">
    <label for="user_photo">Photo</label>
    <input class="form-control" id="user_photo" name="user[photo]" type="file">
  </div>
</div>
```

**Comment by keathley** [comment]
@marcdel Thanks for the detailed report! That helps a ton.

I noticed in your demo app that you're using an umbrella. When you run your tests are you running them from the root of the umbrella or from the web app directory?

**Comment by keathley** [comment]
Actually, nvm on any of that. I figured out the issue. When wallaby attaches a file it uses the absolute path of the file with `:filename.absname(path)`. So when you use `has_value?(relative_path)` it doesn't end up matching.

You can get your tests to pass by doing something like this:

```elixir
  test "can upload a photo", %{session: session} do
    photo_field = file_field("Photo")

    session
    |> visit("/")
    |> attach_file(photo_field, path: "test/support/photo.png")
    |> take_screenshot()

    assert find(session, photo_field, fn (element) ->
      element
      |> Wallaby.Element.value
      |> String.ends_with?("test/support/photo.png")
    end)
  end
```

There might be a better api for this but I'm not sure what it would look like right now.

**Comment by marcdel** [comment]
You know what, I noticed that the test asserts started with “C://“ but my screenshot didn’t show the value getting filled in, so I assumed it was the `attach_file` rather than the assert. In my original project I was also logging the params coming into the controller on submit and that param was missing (but wasn’t when submitting manually). I’ll add a form to this example project and see if that’s the case here as well.

Also, I’d love it if the failure was `expected “integration_test/support/fixtures/file.txt” but got “C:\\fakepath\\file.txt”` rather than `expected true but got false`. I’ll rewrite my tests tonight and if you’d like I can submit a PR that updates those tests’ assertions.

**Comment by keathley** [comment]
Yeah a little more context in that test failure would have made all the difference. Feel free to submit a PR :+1:

**Comment by marcdel** [comment]
I updated my test to do a string comparison of the element value. Turns out it actually is blank 😞

```
test "can upload a photo", %{session: session} do
  photo_field = file_field("Photo")

  session
  |> visit("/")
  |> attach_file(photo_field, path: "test/support/photo.png")
  |> take_screenshot()

  value = find(session, photo_field) |> Wallaby.Element.value()
  assert value == "test/support/photo.png"
end
```

```
1) test can upload a photo (PhotoUploaderWeb.HomePageTest)
     /Users/marc/Code/marcdel/photo_uploader/apps/photo_uploader_web/test/photo_uploader_web/acceptance/photo_upload_test.exs:6
     Assertion with == failed
     code:  assert value == "test/support/photo.png"
     left:  ""
     right: "test/support/photo.png"
     stacktrace:
       /Users/marc/Code/marcdel/photo_uploader/apps/photo_uploader_web/test/photo_uploader_web/acceptance/photo_upload_test.exs:15: (test)
```

**Comment by keathley** [comment]
I think the issue is that you're piping `find(session, photo_field) |> Wallaby.Element.value()` which actually pipes the session into `Wallaby.Element.value`. If you wanna get the value for the element you'll have to use the callback like `find(session, photo_field, & assert Wallaby.Element.value(&1) == "test/support/photo.png")`.

**Comment by marcdel** [comment]
Oh, whoops. I forgot everything is chainable (which is generally v convenient).
Still no dice using a callback though. Either like that or the longer form you posted earlier:
```
find(session, photo_field, fn (element) ->
  assert Wallaby.Element.value(element) == "test/support/photo.png"
end)
```

Somewhat unrelated: I'm having trouble running `integration_test/cases/browser/file_test.exs` in the wallaby repo. If I run `mix test`, all the tests pass. Though nothing I do in that file seems to change that and `IO.puts` statements don't show up, so it seems like maybe they're not being run? When I try to run that file directly I get

```
== Compilation error in file integration_test/cases/browser/file_test.exs ==
** (CompileError) integration_test/cases/browser/file_test.exs:2: module Wallaby.Integration.SessionCase is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    integration_test/cases/browser/file_test.exs:2: Wallaby.Integration.Browser.FileTest (module)
```

**Comment by keathley** [comment]
This works fine for me with you repo:

```elixir
  test "can upload a photo", %{session: session} do
    photo_field = file_field("Photo")

    session
    |> visit("/")
    |> attach_file(photo_field, path: "test/support/photo.png")
    |> take_screenshot()

    find(session, photo_field, fn e ->
      value = e |> Wallaby.Element.value()
      assert value =~ "photo.png"
    end)
```

Wallaby has 2 test suites; a unit suite and an integration suite. In order to run the integration tests you have to specify which browser you want to run against. So it would be something like: `WALLABY_DRIVER=phantom mix test integration_test/cases/browser/file_test.exs`. Also the tag jumping works for me in neovim but I have no idea why it would be different.

**Comment by marcdel** [comment]
That's super weird, so it's gotta be something to do with my webdriver setup or something. At least that narrows down the problem. I'll fiddle with it some more and see if I can get it working. I'll update this issue if/when I do.

Thanks for your help debugging!
