### ISSUE TITLE
Query.text errors on single quotes

### ISSUE THREAD

**Issue by mcasper** [keathley/wallaby#344]
It looks like `Query.text` currently errors if you give it any string with single quotes in it:

```elixir
session
|> visit("/posts")
|> assert_has(Query.text("'"))

=>   ** (Wallaby.QueryError) The text ''' is not a valid query.
     code: |> assert_has(Query.text("'"))
```

This seems to be caused by the fact that `Wallaby.Query.Xpath.text/1` uses single quotes as the delimiter for the selector, and doesn't escape the single quotes in any way.

It seems like it's probably more common to have single quotes in valid text than double quotes, so is there any harm in changing the delimiters to double quotes in this case? Or, working out a way to escape single quotes.

**Comment by keathley** [comment]
We should probably work out a way to escape these correctly since it may be a problem for other selectors as well.

**Comment by mhanberg** [comment]
I am going to start looking into this.
