### ISSUE TITLE
fill_in with emoji value doesn't fill in the input.

### ISSUE THREAD

**Issue by sergiotapia** [keathley/wallaby#346]
Screenshot of failing test: 

![image](https://user-images.githubusercontent.com/686715/35313568-1fa73170-008f-11e8-8f01-f84adcc0bf77.png)

Code:

```
|> fill_in(css("input[placeholder='First Name']"), with: "Sergio 🚀")
|> fill_in(css("input[placeholder='Last Name']"), with: "Tapia 🚀")
```

How can I fill in an input with an emoji? I'm trying to write a test for our validation that prevents emojis from being in the first name and last name fields.

Thanks!

**Comment by keathley** [comment]
@sergiotapia which browser are you using? Chromedriver doesn't handle emoji correctly. We might need to figure out a work around for that in the same way gitlab did: https://about.gitlab.com/2017/12/19/moving-to-headless-chrome/. The TL;DR is that they created a javascript function to fill in the text and fire off DOM events.

**Comment by sergiotapia** [comment]
I'm using chromedriver. I'll take a look at Gitlabs workaround and see how I can apply it to our project, then generalize it for Wallaby.

**Comment by keathley** [comment]
I think the solution here is to add something to the README or wiki about this issue. The correct fix should be upstream in chromedriver. We already have an open PR on this here #348 so I think we can close this and manage the fix there.
