### ISSUE TITLE
version 0.19.2 is much slower than 0.19.1

### ISSUE THREAD

**Issue by sparta-developers** [keathley/wallaby#350]
After upgrading to 0.19.2 from 0.19.1, our test startup time got much much longer.

We created a very simple Phoenix app with `mix phx.new`. We added Wallaby but didn't add any Wallaby tests. Without Wallaby, the tests take 0.0557s. With Wallaby 0.19.1, the tests take 0.925s. With Wallaby 0.19.2, the tests take 14.418s. Here's the repo for that simple app: https://github.com/sparta-science/wallaby_test

We're guessing the slowdown is due to Wallaby waiting for Phantom to start up.

We've noticed this on multiple computers running Mac OS X 10.13.3 (High Sierra) and phantomjs version 2.1.1 (the latest).

Is anyone else seeing this slowdown?

**Comment by keathley** [comment]
I just tested this on my macbook air running sierra 10.12.6. I definitely see an increase in start-up time. Not nearly as bad as 14 seconds though.

Here's what I'm getting:

```
# With 0.19.1
λ time mix test
....

Finished in 0.3 seconds
4 tests, 0 failures

Randomized with seed 91685
        1.54 real         0.95 user         0.47 sys

# With 0.19.2
λ time mix test
....

Finished in 0.09 seconds
4 tests, 0 failures

Randomized with seed 258558
        4.65 real         0.91 user         0.44 sys
```

Those times are pretty consistent on my machine. I'll try to get a system trace to see whats going on. I also suspect that its related to phantomjs startup. We changed that in 0.19.2 to try to fix some issues with zombie phantom processes and it might have caused a slow down.
