### ISSUE TITLE
HTTPoison issue on any URL

### ISSUE THREAD

**Issue by marnen** [keathley/wallaby#351]
I'm running Wallaby 0.19.2 on a Debian Jessie Docker container (hosted on Mac OS X) with Elixir 1.6. Whenever I do `session |> visit(any URL whatsoever)`, I get the following error:

```
** (RuntimeError) Wallaby had an internal issue with HTTPoison
    (wallaby) lib/wallaby/httpclient.ex:32: Wallaby.HTTPClient.make_request/4
    (wallaby) lib/wallaby/phantom/driver.ex:151: anonymous fn/2 in Wallaby.Phantom.Driver.visit/2
    (wallaby) lib/wallaby/driver/log_checker.ex:6: Wallaby.Driver.LogChecker.check_logs!/2
    (wallaby) lib/wallaby/browser.ex:703: Wallaby.Browser.visit/2
```

HTTPoison seems to be retrieving the pages just fine, but I believe the problem is that Wallaby is attempting to decode the resulting HTML as if it were JSON (see https://github.com/keathley/wallaby/blob/v0.19.2/lib/wallaby/httpclient.ex#L54, where the first thing it does is run `Poison.decode(body)`, which fails since the result isn't JSON). Help?

**Comment by marnen** [comment]
On reflection, I'm not sure I'm right about the JSON issue, since I suppose Wallaby would have to be making requests to the PhantomJS endpoint, not directly to the desired HTML page. But I definitely can't get Wallaby to visit _any_ page successfully, even though those pages can successfully be seen by a client such as HTTPoison.

**Comment by marnen** [comment]
Oh, and I'm using PhantomJS 2.1.1 and setting QT_QPA_PLATFORM=offscreen as recommended [here](https://github.com/ariya/phantomjs/issues/14376).

**Comment by marnen** [comment]
I think I was wrong about the root cause here:

```elixir
> {status, %HTTPoison.Response{}} = HTTPoison.get session.url
> status
:ok
>  HTTPoison.post session.url, Poison.encode!(%{url: Endpoint.url})
{:error, %HTTPoison.Error{id: nil, reason: :timeout}}
```

So for some reason the session URL (that's the PhantomJS endpoint, right?) is timing out on POST but not on GET.

**Comment by marnen** [comment]
I think there was a twofold problem.

* I was using the PhantomJS installation from jessie-backports, which doesn't appear to work with Wallaby. I switched to the NPM phantom-prebuilt package.
* I was also setting `QT_QPA_PLATFORM=offscreen` as [required for PhantomJS 2.1.3](https://github.com/ariya/phantomjs/issues/14376). Unfortunately, 2.1.1 (which both backports and the Node package use) don't work if I do that.

So...problem solved by switching to phantom-prebuilt and not setting `QT_QPA_PLATFORM`. Is it worth warning against the jessie-backports version of PhantomJS in the docs?

**Comment by PragTob** [comment]
@marnen thanks for the investigation. It might be worth specifying what version of phantomjs we expect, yes :)

**Comment by marnen** [comment]
Not sure why this was closed, given that the docs were never updated...

**Comment by keathley** [comment]
If you would like to submit a PR that updates the docs then that would be great. Otherwise we're planning on moving to chrome as the default driver since phantom is deprecated so this problem will be lessened.

**Comment by marnen** [comment]
Oh, OK. If this is moot then I won’t bother, but I’ll try to add a sentence or two.
