### ISSUE TITLE
Session details aren't surfaced in test failures

### ISSUE THREAD

**Issue by SherSpock** [keathley/wallaby#352]
It would be helpful if it were possible to surface session details in test failures. Some friends and I just resolved a snag in our project where having some more detailed insight into the DOM state at failure time would have helped a lot.

```test/browser/acceptance_test.exs:69
     ** (Wallaby.ExpectationNotMet) Expected to find 1, visible element that matched the css '#pairing_session' but 0, visible elements were found.
     
     code: |> assert_has(css("#pairing_session", text: "Pairing Session"))
     stacktrace:
       test/browser/acceptance_test.exs:100: (test)```

**Comment by keathley** [comment]
What sort of details would have made it easier for you to diagnose the issue?

**Comment by SherSpock** [comment]
@keathley A little embarrassing, but it was a letter capitalized in our assertion code that was lower-case in the view. We missed it for longer than was really reasonable. If we could have seen that element in the failure we could have potentially caught it instantly.

**Comment by keathley** [comment]
We could potentially return the text from the elements that matched the css so its easier to compare the results.

**Comment by SherSpock** [comment]
@keathley I think that would be super. Some folks might want it toggleable and I don't see much wrong with that. From our side, I think yeah it's worth exploring returning the full or abbreviated content of a matching element

**Comment by keathley** [comment]
Yeah, we're going to have to truncate it in some cases. The "text" of each element includes text of any children elements. We could end up spitting a large amount of content into the users terminal. I guess a small improvement might be to do a levenshtein distance on the text or something. I'll need to think through the ergonomics of that.

**Comment by SherSpock** [comment]
Awesome!

**Comment by SherSpock** [comment]
One of my partners on the project brought #266 to our attention today. The two issues seem to have some overlap. Perfect world -- and I'm just saying this in passing --- it might be nice to see a feature tree related to cleanly rendering the DOM contents, and have this be toggleable on test failure. 

That's excessive for the current case (show me the text in the element being asserted on) but I'm curious if there's more interest in that.

**Comment by keathley** [comment]
I think we can solve a lot of this with #266 so I'm going to close this issue for now and pursue that.
