### ISSUE TITLE
"Can't find variable: Set" error when trying to include jitsi in a system under wallaby test

### ISSUE THREAD

**Issue by tansaku** [keathley/wallaby#353]
Hi there, we're stuck on this error when trying to include jitsi in a system under wallaby test:

https://github.com/AgileVentures/Paironauts/tree/jitsi_working_with_acceptance_tests

It works on two of our developers machines, but not on two others.  We've gone through locking everyone to the same version of elixir (1.6.3), node (9.4) phantomjs (2.1.1) and adding a package-lock.json, but to no avail.

```
     ** (Wallaby.JSError) There was an uncaught javascript error:
     
     ReferenceError: Can't find variable: Set
       e (https://cdn.jitsi.net/2608/libs/lib-jitsi-meet.min.js?v=2608:2)
       (anonymous function) (https://cdn.jitsi.net/2608/libs/lib-jitsi-meet.min.js?v=2608:2)
       (anonymous function) (https://cdn.jitsi.net/2608/libs/lib-jitsi-meet.min.js?v=2608:2)
```

Any ideas how we could further lock things down to have this pass on all developer machines?

Many thanks in advance

**Comment by keathley** [comment]
Can you vendor the package instead of pulling from the cdn? That might help eliminate some of the variables. Otherwise, I'm not sure what the issue would be. I've never used that JS library.

**Comment by PragTob** [comment]
This looks more like an actual JS error with the library that should also occur in normal browser usage versus a wallaby error. Wallaby just reports that a JS error happens. The most likely case as to why it wouldn't occur in a normal browser would be that it relies on some feature that phantomjs doesn't support yet.

Also, loading race conditions or whatever seem likely.

**Comment by tansaku** [comment]
thanks @PragTob - there's no error in the browser, the jitsi all works perfectly fine with no errors in consoles across several browsers.

Note also that wallaby reports no errors at all on two of our developer machines (one OSX, one ubuntu), but does on two others (both OSX).  Phantomjs is the same version on all machines, so we are looking for sources of variance across those machines.  They are locked to the same version or elixir, phoenix, phantomjs etc. - only thing we can think of at the moment is that there are different node_modules loaded on the different machines, but locking node version and packages doesn't seem to have any impact unless we are misunderstanding how phoenix manages node modules.

@keathley thanks, I guess we can look into vendoring the package, although we didn't write the jitsi stuff and we're using it in the recommended fashion.  It seems odd to be adjusting the app to support the tests, when as I say, the tests all pass with no js error at all on two of our developer machines, but error out on two others.

So my question is less about the error per say, than how to we can lock down dependencies for the app ... logically there must be some difference between the machines on which this test passes and the ones where it doesn't ...

**Comment by keathley** [comment]
I’m sure y’all have done this but you’ve tried removing all node modules, re-downloading, and ensured that everything is recompiled before testing? That might help to eliminate variables.

**Comment by tansaku** [comment]
@keathley yeah, done that a few time ... :-/

**Comment by keathley** [comment]
How are you installing phantomjs? Are there any sort of issues that might cause the cdn to be unreachable for some of those machines? If you vendor the library does that make the problem go away? If vendoring the library works then we can at least pinpoint the problem to the network / cdn and not to some other variable.

**Comment by tansaku** [comment]
thanks @keathley - jitsi didn't seem to easily go for vendoring.  We seem to have fixed the issue by using a more recent beta version of phantomjs that supports ES6 https://www.npmjs.com/package/phantomjs25-beta - thanks to @bcb37 for working this out ...

**Comment by keathley** [comment]
Rad, glad you got it sorted out 👍.
