### ISSUE TITLE
Format using elixir code formatter

### ISSUE THREAD

**Issue by opsb** [keathley/wallaby#356]
Would be convenient for future PRs :) I'd have PR'd it myself but it would have skewed my contribution stats somewhat ;)

**Comment by opsb** [comment]
Yeah, I agree there areas where the formatting could be a little nicer (it's not quite on par with elm-format yet), on balance though having consensus easily trumps those niggles for me (my 2 cents).

**Comment by PragTob** [comment]
Sadly true :)

**Comment by keathley** [comment]
I'm fine if someone else wants to run the formatter on wallaby but I have no intention to do it myself. As of right now I think the formatter generates less consistent and less understandable code then the majority of people contributing to this project. I trust all of y'alls ability and so far I've found all of your code very readable 😄 . If someone else feels strongly about it I'm certainly not going to reject the PR. I'm just not going to take the time to make one atm.

**Comment by keathley** [comment]
Closing this for now. I think at this point its happening file by file as people are doing development.
