### ISSUE TITLE
Iterating over multiple elements - timeout error

### ISSUE THREAD

**Issue by coop** [keathley/wallaby#357]
I'm sorry if this is the wrong place for support questions but I couldn't find a link to a slack / irc so I thought I'd post here - if this is not appropriate please let me know where I should ask questions.

I am receiving timeout errors (first from postgres and then from exunit) when trying to navigate and fill in forms. Specifically I have the following structure:

index page (lists blog posts)
show page (contains a form for updating the blog post)

And I'd like to write an automated test that visits each of the blog posts on the index page and submit their form (I just want to submit the form). The code I have is as follows:

```ex
session
|> visit(Routes.root_path(@endpoint, :root)) # list all blog posts
|> find(Query.css(".post", count: 5), fn(elements) -> # each blog post is in a <div class="post">
  Enum.each(elements, fn(element) ->
    element
    |> click(Query.link("view post")) # navigates to the show action for the blog post
    |> click(Query.button("Save")) # presses the save button to submit the form
  end)
end)
|> assert_all_posts_are_done # saving a post marks it "done" and I will check for 5 "done" posts on the index page
```

Everything works right up until `|> click(Query.link("view post"))`, as soon as the link is clicked the test seems to timeout and I receive:

```
22:29:17.711 [error] Postgrex.Protocol (#PID<0.403.0>) disconnected: ** (DBConnection.ConnectionError) owner #PID<0.592.0> timed out because it owned the connection for longer than 15000ms
```

(If I let the test run for 60s I'll also get the ExUnit timeout error message)

I'm obviously approaching this problem wrong, any guidance would be appreciated. Even some updated documentation on iterating over multiple elements in the documentation would be great.

**Comment by keathley** [comment]
Does clicking the link navigate the browser to a new page?

**Comment by keathley** [comment]
Sorry, I'll add more clarity here. In your `Enum.each` the `element` is a specific reference to a DOM element on the page. If the link is navigating to a new page (as opposed to just doing something with JS) then that specific element isn't present on your page. So you can't use it in your `click(Query.button("Save")` call.

**Comment by coop** [comment]
@keathley you are correct that `element` is on the index page, clicking "view post' navigates to a new page.

>If the link is navigating to a new page (as opposed to just doing something with JS) then that specific element isn't present on your page. So you can't use it in your click(Query.button("Save") call.

So how do I rewrite this so it "works"? I have tried passing in `session` instead of of `element` to `click(Query.button("Save"))` like so:

```ex
session
|> visit(Routes.root_path(@endpoint, :root)) # list all blog posts
|> find(Query.css(".post", count: 5), fn(elements) -> # each blog post is in a <div class="post">
  Enum.each(elements, fn(element) ->
    element
    |> click(Query.link("view post")) # navigates to the show action for the blog post

    session
    |> click(Query.button("Save")) # presses the save button to submit the form
  end)
end)
```

This still gives me the same error. In fact I get the error just by clicking on "view post":

```ex
session
|> visit(Routes.root_path(@endpoint, :root)) # list all blog posts
|> find(Query.css(".post", count: 5), fn(elements) -> # each blog post is in a <div class="post">
  Enum.each(elements, fn(element) ->
    element
    |> click(Query.link("view post")) # navigates to the show action for the blog post
end)
```

I guess that sort of makes sense as it's the second iteration of the loop that is erroring because the following doesn't error:

```ex
session
|> visit(Routes.root_path(@endpoint, :root)) # list all blog posts
|> find(Query.css(".post", count: 5), fn(elements) -> # each blog post is in a <div class="post">
  elements
  |> List.first
  |> click(Query.link("view post")) # navigates to the show action for the blog post
end)
```

So I guess I have a better understanding of why the error is happening but not how to solve my problem which I think I now have two of.

1. given my last example (with `List.first`) how do I click the "Save" on the second page?
2. given multiple elements (`find(Query.css(".post", count: 5))`) how do I iterate over each one, navigate to the show page and submit the form? (I think I want some kind of scope reset)

**Comment by keathley** [comment]
Without more context here's how I would probably structure it:

```elixir
visit(session, Routes.root_path(@endpoint, :root))
for i <- 0..4 do
  find session, css(".post", count: 5, at: i), fn post ->
    click(post, link("view post"))
    click(session, button("save"))
  end
end
```

**Comment by coop** [comment]
Ok, I seem to have answered question [1] - when navigating to a new page you need to pass in `session` not the result of `click(Query.link(...))` like so:

```ex
session
|> visit(Routes.root_path(@endpoint, :root)) # list all blog posts
|> find(Query.css(".post", count: 5), fn(elements) -> # each blog post is in a <div class="post">
  elements
  |> List.first
  |> click(Query.link("view post")) # navigates to the show action for the blog post

  session
  |> click(Query.button("Save"))
end)
```

It wasn't obvious that I needed to reset the session when visiting a new page. Your [example](https://github.com/keathley/wallaby/issues/357#issuecomment-373532287) was a great help. I have modified your example to support an unknown number of posts:

```ex
visit(session, Routes.root_path(@endpoint, :root))
number_of_posts = find session, css(".post", count: :any)
for i <- 0..(number_of_posts - 1) do
  find session, css(".post", count: number_of_posts, at: i), fn post ->
    click(post, link("view post"))
    click(session, button("save"))
  end
end
```

And this also works.

@keathley I appreciate the feedback, passing in `session` to a new page was the part that I was missing. Thanks.
