### ISSUE TITLE
Switch to puppeteer

### ISSUE THREAD

**Issue by sphinxc0re** [keathley/wallaby#358]
https://github.com/GoogleChrome/puppeteer seems to be much better maintained and stable than PhantomJS

**Comment by PragTob** [comment]
We already have experimental support for headless chrome itself... I don't see much benefit from using puppeteer then or am I missing something?

**Comment by sphinxc0re** [comment]
Oh, I did not know that. Is there any documentation regarding that?

**Comment by PragTob** [comment]
it's right in the README https://github.com/keathley/wallaby#experimental-driver-support

**Comment by keathley** [comment]
At some point we may try to support the underlying DevTools api. But in true Google fashion its specific only to chrome and isn't apart of any standard so we can't use it for all browsers. Puppeteer seems like a fine library if you're using JS but isn't very useful for our purposes atm.
