### ISSUE TITLE
Make our test suite more reliable in CI

### ISSUE THREAD

**Issue by keathley** [keathley/wallaby#359]
Right now we get a lot of failing CI tests because our test build isn't very reliable. I propose that we drop support for all elixir and erlang versions other then the latest. I don't think we've ever found an issue in one elixir version and not in another. We can flex on that rule if it makes sense to do so for specific use cases but as of right now I think we're just inviting more issues.

I also think we need to make our builds more reliable. There are many times where a build will fail simply because it couldn't download chromedriver or selenium. Making that more reliable would go a long way towards both speeding up our CI builds and also making them more reliable.

**Comment by carl-al** [comment]
@keathley Agree with this. Surely supporting 2-3 minor versions behind, with latest patches is enough? With latest support and 3 patches to the latest?  So on this note, we should support Elixir  

v1.6.5 OTP 20
v1.6.4 OTP 20  _**optional_
v1.5.3 OTP 20 
v1.4.5 OTP 20

v1.6.5 OTP 19
v1.5.3 OTP 19
v1.4.5 OTP 19


**Selenium**
Second, Selenium version 2 is riddled with issues and lack of support for today's JS needs. Would you consider dropping this too? Especially as version 3 has been around for over two years now. 

Version 2.53.1 was last updated in July 2016.
https://github.com/SeleniumHQ/selenium/releases/tag/selenium-2.53.1

Interesting read:
https://techbeacon.com/selenium-30-40-50-roadmap-finally-unveiled
Looks like work is underway for version 4, see:  https://www.npmjs.com/package/selenium-webdriver

**Travis**
We also noticed that there is no elixir container in https://hub.docker.com/u/travisci/ 

There are a lot of workarounds required to get going. We have a lot of experience with CircleCI and it is very flexible around docker containers, where you can create specific wallaby docker images if required via docker-hub. Take a look at: 
- https://github.com/circleci/circleci-images
- https://github.com/CircleCI-Public/circleci-dockerfiles

We do not work for CircleCI btw, we just use the tools and are happy to help to move over to something more flexible. Plus re-running tests and digging into issues on a command line we like a lot. Running the build locally is super simple, and takes little effort compared to Travis. We do this a lot. Something to consider. 

CircleCI is free for opensource https://circleci.com/pricing/#faq-section-linux

Thanks 
Carl

**Comment by keathley** [comment]
@aaronrenner would be the person to talk to about dropping selenium 2 support. I don't have a strong opinion on it one way or the other.

I have a lot of experience with circle ci and I'm not against moving there. But we'll still need to do the work of building docker containers that include our drivers, etc. regardless of where we run our tests.

**Comment by daveed** [comment]
First iteration @keathley and @aaronrenner for the build on CircleCI using elixir 1.6.5 and phantom.
My fork is at https://github.com/daveed/wallaby/pull/1 and CircleCI at https://circleci.com/gh/daveed/wallaby/2
Will add elixir versions using `asdf` and CircleCI Workflows to test different elixir versions and web drivers and more.

**Comment by keathley** [comment]
@daveed Are you still interested in pursuing this?

**Comment by daveed** [comment]
I am @keathley

**Comment by michallepicki** [comment]
Closing in favor of https://github.com/keathley/wallaby/issues/418
