### ISSUE TITLE
Attempting to visit without setting the base_url should raise an error

### ISSUE THREAD

**Issue by paulcsmith** [keathley/wallaby#36]
At first, I missed the instructions for setting the base_url. So when I did `visit("/my_path")` it did not visit my app.

I think that if you use relative paths without a base_url an error should be raised

```
You called visit with #{relative_path}, but did not set a base_url

Set this somewhere in your app, maybe in test/test_helper.exs:

    Application.put_env(:wallaby, :base_url, "http://localhost:4001")

If using Phoenix, you could grab the url from your endpoint:

    Application.put_env(:wallaby, :base_url, YourApplication.Endpoint.url)
```

**Comment by keathley** [comment]
This seems like a great idea to me. Should be simple enough to implement. Just check for a relative path and then throw the exception if there is no base_url.

**Comment by keathley** [comment]
This is in the latest release (0.5.0). Thanks again for the suggestion!

**Comment by paulcsmith** [comment]
Woo hoo! Thanks for releasing so fast. That's awesome :D
