### ISSUE TITLE
Don't fail (or ignore) on JS warnings?

### ISSUE THREAD

**Issue by johnmosesman** [keathley/wallaby#366]
Is it possible to configure wallaby to ignore JS warnings, but not errors? Due to an aggressive React warning on a valid element (HTML 5 video `<source>` tag) our tests are failing.

```
** (Wallaby.JSError) There was an uncaught javascript error:

Warning: The tag <source> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
printWarning (http://localhost:4001/js/app.js:21268)
```

**Comment by keathley** [comment]
You can add `js_errors: false` to to your wallaby config in order to disable errors causing test failures. Let me know if that doesn't solve your issue :+1:.

**Comment by johnmosesman** [comment]
Hmm ideally there would be a way to differentiate between warnings and errors--as an unexpected error is probably something worthy of failing on--but I can see how that would be difficult to determine.

**Comment by keathley** [comment]
Ah, sorry, I was probably too hasty and didn't fully understand the issue. The errors are captured here: https://github.com/keathley/wallaby/blob/master/lib/wallaby/phantom/logger.ex#L5. We might be able to reliably determine if the message is a warning or an error there.
