### ISSUE TITLE
save_and_open_page a missing feature of capybara

### ISSUE THREAD

**Issue by carl-al** [keathley/wallaby#372]
Hi 

I have a series of helpers that I would like to share however want to start with a simple tool we use a lot. That is the `save_and_open_page` feature inspired by the same feature in capybara for ruby which can be found here:

https://github.com/teamcapybara/capybara/blob/e8b49b6eed31547ab3138b6c18ecc423b1ae5405/lib/capybara/session.rb#L691

We have it as a helper but thought if you wanted to add the feature where do you want it to go?

`wallaby/lib/wallaby/helpers/session ?`

Happy to discuss implementation, our helper as simple as it is, is below:

```
defmodule Wallaby.Helpers.Session do
  import Wallaby.Browser

  def save_and_open_page(session, wait_time \\ 600_000, open_file? \\ true, cleanup? \\ false) do
    {:ok, response} = Wallaby.HTTPClient.request(:get, "#{session.url}/source")
    page_source_data = response["value"]

    name = [] |> Keyword.get(:name, :erlang.system_time) |> to_string
    path = path_for_page_source(name)
    File.write!(path, page_source_data)
    case open_file? do
      true -> System.cmd("open", [path])
      false -> :noop
    end
    Process.sleep(wait_time)
    case cleanup? do
      true -> File.rm_rf(path)
      false -> :noop
    end
  end

  defp path_for_page_source(name) do
    File.mkdir_p!(page_source_dir())
    "#{page_source_dir()}/#{name}.html"
  end

  defp page_source_dir do
    Application.get_env(:wallaby, :screenshot_dir) || "#{File.cwd!()}/pages"
  end
end
```

If we can discuss the implementation and where you want it to go, I can submit a PR with appropriate tests for the feature

- `wait_time` is used to keep the server going so you can inspect whats going on. 
- `open_file?` is set to true to open the file, your system default browser should open it
- `cleanup` is set to false by default, but if you want to clean-up after the time-out

Let me know

Thanks in advance
Carl

**Comment by keathley** [comment]
Thanks @carl-al. I think this looks like a worthwhile feature. If you want to open a PR we can discuss implementation details there. One thing to think is if this should be a "chainable" action. In which case we'll want to return the session from this function so that it can be joined with other actions in a pipeline like so:

```elixir
session
|> save_and_open_page
|> find(...)
```

Thanks 👍!
