### ISSUE TITLE
Phantomjs - Wallaby had an internal issue with HTTPoison 

### ISSUE THREAD

**Issue by nelson687** [keathley/wallaby#375]
I'm using wallaby to scrape different links from a page, and I'm trying to do this in parallel using Task.async and Task.await, in total there are 38 links I want to spawn in parallel, but in order to test I started with only 2:

```
all(page, css("#id1 #id2 ul li a"))
|> Enum.slice(0, 2) #testing with 2 elements only
|> Enum.map(&(Task.async(fn -> get_elements(&1) end)))
|> Enum.map(&Task.await(&1, 20000))
```
and
```
defp get_elements(round_link) do
        link = attr(round_link, "href")
        {:ok, session} = Wallaby.start_session
        visit(session, link)
        match_date = get_first_date(session) # this is just using Floki to scrape some data from the html
        Wallaby.end_session(session)
        match_date
end
```

this works, but when I change `Enum.slice(0, 2)` to more than 2, I get this error
```
14:21:58.343 [error] Task #PID<0.262.0> started from #PID<0.254.0> terminating
** (RuntimeError) Wallaby had an internal issue with HTTPoison
    (wallaby) lib/wallaby/httpclient.ex:32: Wallaby.HTTPClient.make_request/4
    (wallaby) lib/wallaby/phantom/driver.ex:156: anonymous fn/2 in Wallaby.Phantom.Driver.visit/2
    (wallaby) lib/wallaby/driver/log_checker.ex:6: Wallaby.Driver.LogChecker.check_logs!/2
    (wallaby) lib/wallaby/browser.ex:707: Wallaby.Browser.visit/2
    (crawlixir) lib/crawler.ex:21: Crawler.get_elements/1
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<2.84801462/0 in Crawler.get/1>
    Args: []
```

I have phantomjs 2.1.1 installed, Elixir 1.5.1 and Erlang 20

I've seen this happening for chrome, but I guess it should be working fine for phantomjs.

**Comment by nelson687** [comment]
Just tried without spawning new processes for each link and it works
```
all(page, css("#col-resultados #desplega_jornadas ul li a"))
        |> Enum.slice(0, 10)
        |> Enum.map(&get_elements(&1))
```

so it seems the issue is when running multiple Wallaby browser sessions

**Comment by keathley** [comment]
Typically this happens when we overrun the webdriver with requests as happens when running lots of requests in parallel. I've been trying to make this more reliable with retries. But we probably need to include backoff and jitter in wallaby's request handling to make this more robust.

**Comment by jeroenhouben** [comment]
Why is the httpoison dep still on 0.x ?

It's already at 1.2.0 https://github.com/edgurgel/httpoison/blob/master/mix.exs

**Comment by keathley** [comment]
@jeroenhouben see https://github.com/keathley/wallaby/pull/369

**Comment by nelson687** [comment]
Is this a webdriver issue or something specific to this library? I mean, are we constraint by webdriver or is there any space for improvement?

**Comment by keathley** [comment]
@nelson687 We get these errors because the different webdrivers can't handle the amount of concurrent requests we throw at them. We can help this by doing backoff with jitter in our retry logic.

**Comment by keathley** [comment]
I've opened a PR that _may_ help to alleviate some of these issues. Otherwise I'm going to close this for now and move the discussion to #365. At this time I believe that they are related issues.
