### ISSUE TITLE
Include what failed in failure messages

### ISSUE THREAD

**Issue by paulcsmith** [keathley/wallaby#38]
So if you call `click("Submit")` and it fails:

```
Could not click "Submit" because it was not found on the page
```

Would be extra cool if it found all the link text on the page and used `String.jaro_distance` to find potential mispellings. 

```
Could not click "Submit" because it was not found on the page

Did you mean "submit"?
```

It could potentiall work the same for CSS

```
Could not find ".my-css"
```

If you spelled it wrong

```
Could not find ".my-css"

Did you mean ".my_css"?
```

These problems come up a lot so these error messages would be insanely useful!

**Comment by keathley** [comment]
I *love* this idea.

Some things that come to mind that we'll need to address:

* Each finder will have to know how to do a generic search for any matching types. For instance links have to know how to look for all links, css finders have to find all nodes with matching css attributes.
* Finding css could be tricky if its a nested selector. I'm thinking of something like `.foo .bar .my_css`.
* We'll have to define correct semantics for nested selectors. If we have something like:

```elixir
find(".user-form")
|> click "Submit"
```

and it doesn't match the button text correctly then IMO it should only look for alternatives inside of the `.user-form`.

I don't think any of these things should/would keep us from implementing this feature.

**Comment by paulcsmith** [comment]
I'm glad you like the idea. That seems like a good analysis to me. I agree that the "did you mean" should be scoped to the node and not the whole page when a node is given.

Nested CSS selectors might be tricky. If it's too hard then you could skip "did you mean" if the selector is nested (has any spaces). That way people at least get the benefits for non-nested CSS selectors?

**Comment by keathley** [comment]
I think thats probably fair. Lets start by just checking for alternatives for single selectors and for text. I think that allowing for nested selectors is going to be more of a time investment and I'd like to start experimenting with this feature.

**Comment by keathley** [comment]
Some of these features have been included since this was opened and there are specific issues for further improving our error messages. Going to close this in favor of continuing the discussion there.
