### ISSUE TITLE
The function refute_has didn't wait for the element to disappear

### ISSUE THREAD

**Issue by yonst** [keathley/wallaby#422]
## Issue

Unlike the assert_has function, when the element is not found it performs retry and waits to see if the element will appear, the refute_has function returns an immediate error.
This is because both functions use the same auxiliary function -
execute_query that returns an error to retry only if the element is not found.

Fix suggestion: add an opposite function to execute_query that returns an error if the element is found and ok if not.
![Screen Shot 2019-03-27 at 15 58 36](https://user-images.githubusercontent.com/26692692/55082264-0a5c6300-50aa-11e9-9529-af3fc5e447f8.png)
![Screen Shot 2019-03-27 at 15 59 03](https://user-images.githubusercontent.com/26692692/55082293-16e0bb80-50aa-11e9-8686-6d4912058a3c.png)

**Comment by keathley** [comment]
Hey @yonst! Thanks for the suggestion. We've actually talked about removing `refute_has` altogether for exactly this reason. Generally the better idea is to specify that there should be 0 of an element or that the element should be invisible in the query and continue to use `assert_has`. I think long term that will lead to less surprises and a better interface. Thanks for the suggestion though :+1:

**Comment by juffel** [comment]
You could use [`find`](https://hexdocs.pm/wallaby/Wallaby.Browser.html#find/2) and combine it with a `Query` with `count: 0` parameter to get this blocking behaviour.
This 👇 will wait until there are no links that are called "disappearing-link" anymore (at least until it times out). 

```elixir
find(session, Query.link("disappearing-link", count: 0))
```
