### ISSUE TITLE
Ability to set host header with Chromedriver

### ISSUE THREAD

**Issue by AndroidOatmeal** [keathley/wallaby#430]
Our team would like to make the switch from phantomjs to chromedriver, due to ongoing issues with the wallaby phantom driver (see [this issue](https://github.com/keathley/wallaby/issues/423)).

Our app is multi-tenant with a different subdomain per tenant. With the phantom driver, we were able to set a custom host header with a function like this:

```
  def custom_domain_session(host) do
    host = "#{host}:4001"
    custom_headers = %{"Host" => host}
    metadata = Phoenix.Ecto.SQL.Sandbox.metadata_for(MyApp.Repo, self())
    Wallaby.start_session(custom_headers: custom_headers, metadata: metadata)
  end 
```

However, this function doesn't work for the chrome driver. I dug around the Wallaby codebase a bit, and it appears that the Chromedriver doesn't support setting a custom host when starting a session.

Are there any known workarounds for this? Could this feature be added to the project?

**Comment by michallepicki** [comment]
I also was researching this topic for usage with Selenium, and the only solutions I could find were using custom browser extensions or HTTP proxies.

**Comment by keathley** [comment]
@AndroidOatmeal I agree with @michallepicki. I'm not sure we can do this with chromedriver or selenium. I was thinking about it a bit and was wondering how you set the host header under normal usage. I wonder if we can solve your problem in a slightly different way.

**Comment by AndroidOatmeal** [comment]
@keathley We have a plug in our router called `FetchTenant`. This plug parses the subdomain from  `conn.host`, and puts the tenant in the conn's assigns. This way any request that hits one of our subdomains will correctly assign the correct tenant.

**Comment by keathley** [comment]
Is it possible to just always tell wallaby to go to a specific tenant? It looks like you're already doing that in your test setup. I think I'm missing some information here. Shouldn't you just need to tell wallaby what url to go to?

**Comment by AndroidOatmeal** [comment]
Sorry for the confusion. Let me explain more clearly.

Let's say I'm writing a local acceptance test to ensure that some data is not shared across tenants. I want to do something like:

```
def custom_domain_session(host) do
  host = "#{host}:4001"
  custom_headers = %{"Host" => host}
  metadata = Phoenix.Ecto.SQL.Sandbox.metadata_for(MyApp.Repo, self())
  Wallaby.start_session(custom_headers: custom_headers, metadata: metadata)
end

test "new posts are not shared across tenants" do
  foo_tenant_session = custom_domain_session("foo.example.local")
  bar_tenant_session = custom_domain_session("bar.example.local")

  # Foo tenant user adds a new post
  foo_tenant_session =
    foo_tenant_session
    |> visit("/posts")
    |> click(Query.button("New Post"))
    |> fill_in(Query.text_field("Title"), with: "New Post")
    |> fill_in(Query.text_field("Text"), with: "My great new post")
    |> click(Query.button("Submit"))

  # Foo tenant user can see new post
  assert foo_tenant_session |> visit("/posts") |> has_text?("My great new post")

  # Bar tenant user cannot see the Foo tenant's posts
  refute bar_tenant_session |> visit("/posts") |> has_text?("My great new post")
end
```

We have some pre-existing special entries in `/etc/hosts` to facilitate this:
```
127.0.0.1	foo.example.local
127.0.0.1	bar.example.local
```

We need to handle these requests differently based on what "host" they're trying to access. Under the hood, there is still a single server, of course. In production we have multiple domains pointing towards our single app instance. The `FetchTenant` plug I mentioned earlier allows us to support multitenancy in this way.


The problem right now is that the Wallaby phantomjs driver allowed us to set the host via custom headers, while the Wallaby Chromedriver does not appear to support this.

**Comment by michallepicki** [comment]
@AndroidOatmeal Why is your plug based on headers and not just the domain?

**Comment by AndroidOatmeal** [comment]
@michallepicki Our plug doesn't do anything with headers directly. We just grab the `host` field from our `%Plug.Conn{}` and use a regex to parse out the subdomain. Then we look up that subdomain in the database to find the corresponding tenant, or we display an error if no such tenant exists. Nothing fancy there.

Here's a simplified version of what we're doing, in case it helps.

```
defmodule MyAppWeb.FetchTenantPlug do
  import Plug.Conn

  alias Phoenix.Controller
  alias Plug.Conn
  alias MyApp.Tenants.Tenant

  def init(opts), do: opts

  def call(conn, _opts) do
    subdomain = parse_subdomain(conn)
    tenant = subdomain && Repo.get_by(Tenant, subdomain: subdomain)

    case tenant do
      %Tenant{} = tenant ->
        assign(conn, :tenant, tenant)

      nil ->
        conn |> redirect_and_halt
    end
  end

  defp parse_subdomain(%Plug.Conn{host: host}) do
    captures = Regex.named_captures(~r/^(?<subdomain>[a-z\-]*)\.[^.]*\.(com|local)/, host)

    case captures do
      %{"subdomain" => subdomain} -> subdomain
      _ -> nil
    end
  end

  defp redirect_and_halt(conn) do
    conn
    |> Controller.put_flash(:info, "Make sure the link you used has the correct subdomain.")
    |> Controller.redirect(to: "/")
    |> Plug.Conn.halt()
  end
end

```

**Comment by michallepicki** [comment]
@AndroidOatmeal Can you use `Wallaby.Browser.visit` passing the absolute path (full URL containing the subdomain)? Would this work instead of setting the header?

**Comment by keathley** [comment]
@AndroidOatmeal I was going to mention the same thing that @michallepicki did. If you pass the full url to `visit` Wallaby will use that instead of whatever base url you've specified.

In your test you could do something like this:

```elixir
foo_tenant_session =
    session
    |> visit("http://foo.example.local/posts")
    |> click(Query.button("New Post"))
    |> fill_in(Query.text_field("Title"), with: "New Post")
    |> fill_in(Query.text_field("Text"), with: "My great new post")
    |> click(Query.button("Submit"))
```

If you've already updated your `/etc/hosts` file then this should work out. Otherwise you'll probably have to get a little fancier in your setup. But I suspect that you'll have to do that for local development anyway. I know when I've had to work on multi-tenant apps like this in the past I've had to do something similar.

**Comment by AndroidOatmeal** [comment]
@keathley @michallepicki Thanks so much for your input guys. This solution hadn't occurred to me. I tried it out and it worked perfectly.

Some feedback: it might be nice for Wallaby to support multi-tenancy as a first-class feature. Your proposed solution works for us, but we still need to juggle separate URLs and sessions whenever we use `visit/2`. I could imagine providing an optional `base_url` param to `start_session/1`, which would get prepended whenever you use `visit/2`. Something to think about. 🤔 

Thanks again for all your help on this!

**Comment by michallepicki** [comment]
I'm glad we were able to help! :)

I'm not currently testing multi-tenant apps, but you can configure the `base_url` in Wallaby already:
```
# test/test_helper.exs
Application.put_env(:wallaby, :base_url, YourApplication.Endpoint.url)
```

Instead of using `YourApplication.Endpoint.url` you could read from system environment variables or have other Elixir code for setting it.

In my case I need to slightly change the base url depending on which test is running, so I'm doing something more similar to what you described. As a part of setup in my feature case I'm figuring out `base_url` and passing it along with session to the test, like this:
```
setup tags do
    {:ok, session} = Wallaby.start_session(
      # ...
      # other setup stuff

    {:ok, session: session, base_url: base_url(tags)}
  end

  def base_url(tags) do
    # if something is set in tags for this test, do something
    else
      "https://subdomain.example.com/"
    end
  end
```
