### ISSUE TITLE
Instructions for setting up wallaby for an umbrella app don't work

### ISSUE THREAD

**Issue by 7stud** [keathley/wallaby#433]
## Issue

**phantomJS**:
I installed the latest phantomJS with npm:
```
~$ npm list -g --depth=0
/Users/7stud/.nvm/versions/node/v11.2.0/lib
├── npm@6.9.0
└── phantomjs-prebuilt@2.1.16
```
**Versions:**
```
~/phoenix_apps/auction_umbrella$ iex
Erlang/OTP 20 [erts-9.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Interactive Elixir (1.8.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 
```

When I run `mix text`, I get this error:

```
  ** (RuntimeError) cannot invoke sandbox operation with pool DBConnection.ConnectionPool.
     To use the SQL Sandbox, configure your repository pool as:
     
         pool: Ecto.Adapters.SQL.Sandbox
```

The docs start off nicely using two names to distinguish between the two apps in an umbrella app:

> Umbrella Apps
> 
> If you're testing an umbrella application containing a Phoenix application for the web interface (MyWebApp) and a separate persistence application (MyPersistenceApp) using Ecto 2 with a database that supports sandbox mode, then you can use the same setup as above, with a few tweaks.

But then comes this:

> **Writing tests** 
> 
> It's easiest to add Wallaby to your test suite by creating a new case template (in case of an umbrella app, take care to adjust YourApp appropriately):
> 
> ```
> defmodule YourApp.FeatureCase do
>   use ExUnit.CaseTemplate
> 
>   using do
>     quote do
>       use Wallaby.DSL
> 
>       alias YourApp.Repo
>       import Ecto
>       import Ecto.Changeset
>       import Ecto.Query
> 
>       import YourApp.Router.Helpers
>     end
>   end
> 
>   setup tags do
>     :ok = Ecto.Adapters.SQL.Sandbox.checkout(YourApp.Repo)
> 
>     unless tags[:async] do
>       Ecto.Adapters.SQL.Sandbox.mode(YourApp.Repo, {:shared, self()})
>     end
> 
>     metadata = Phoenix.Ecto.SQL.Sandbox.metadata_for(YourApp.Repo, self())
>     {:ok, session} = Wallaby.start_session(metadata: metadata)
>     {:ok, session: session}
>   end
> end
> ```
> 

The name `YourApp` is indeterminate and could be either of these three things:  

1. MyUmbrellaApp
2. MyWebApp
3. MyPersistenceApp

Or some combination?  Who knows.

**Comment by keathley** [comment]
Is there a question here? Can you explain your situation and what exactly isn't working?

**Comment by 7stud** [comment]
No, there is no question, but I did post an error I got.  I will never use Wallaby again because I don't have time to deal with poorly documented packages.  I don't care how great a programmer you are--if you can't explain how to use your genius create works, then your software is worthless.  

If you don't care about the error message, then we are even.

**Comment by keathley** [comment]
You posted a critique of the documentation without providing any other actionable feedback. The error message you gave doesn't contain nearly enough information for me to help you. You chose to be antagonistic. If you want help and respect you have to be willing to give a little of both yourself.
