### ISSUE TITLE
Simulate Drag and Drop From Filesystem

### ISSUE THREAD

**Issue by zolrath** [keathley/wallaby#44]
I've split this into its own issue as from what I've read its a harder issue to solve.

It'd also be very nice to be able to test drag and drop file uploaders by allowing us to easily specify that we've dropped a file onto a specific element.

**Comment by keathley** [comment]
I'm not sure what an implementation for this would really look like. Just thinking through some ideas. One way to simulate drag and drop file uploads would be to first create a new input file in the DOM, attach a file to that new input node, and then simulate the required drag and drop events.

I'm not sure if that solution would work for all drag and drop file uploaders though. And there is probably something that I'm forgetting.

If you want try implementing this then I'd be happy to help work through the details.

**Comment by keathley** [comment]
I'm not sure of a reliable way for us to simulate this so I'm going to close this issue for now. If anyone knows of a way to do this feel free to re-open the issue.
