### ISSUE TITLE
Don't ship safe_travis.ex

### ISSUE THREAD

**Issue by PragTob** [keathley/wallaby#451]
```
==> wallaby
Compiling 34 files (.ex)
warning: function Mix.Tasks.Coveralls.do_run/2 is undefined (module Mix.Tasks.Coveralls is not available)
  lib/mix/tasks/safe_travis.ex:11
```

we shouldn't ship that task in the released hex.pm package.

Maybe I'll get to it but I have a busy weekend in front of me.

**Comment by mhanberg** [comment]
How would one accomplish this? I am about to cut the next release and would like to get this in there if possible.

**Comment by michallepicki** [comment]
Looks like it's documented here: https://hexdocs.pm/hex/Mix.Tasks.Hex.Publish.html#module-package-configuration

**Comment by mhanberg** [comment]
Yeah, that shows how to include files, but not exclude them.

**Comment by michallepicki** [comment]
I'll try to figure it out and send a PR
