### ISSUE TITLE
Vague "invalid session id" error with no context

### ISSUE THREAD

**Issue by AndroidOatmeal** [keathley/wallaby#452]
Hello!

I am running a simple acceptance test that submits a form and updates a model. I think I have a bug somewhere in my controller/router logic, so this particular step in my test fails (which is fine, as I'm TDDing this feature.)

However, wallaby is blowing up with a very vague error at this step:

```
** (EXIT from #PID<0.90.0>) exited in: GenServer.stop(#PID<0.643.0>, :normal, 30000)
    ** (EXIT) exited in: :sys.terminate(#PID<0.643.0>, :normal, :infinity)
        ** (EXIT) exited in: GenServer.call(Wallaby.Driver.LogStore, {:get_and_update, #Function<0.5365077/1 in Wallaby.Driver.LogStore.append_logs/2>}, 5000)
            ** (EXIT) an exception was raised:
                ** (ArgumentError) argument error
                    :erlang.--(%{"error" => "invalid session id", "message" => "invalid session id", "stacktrace" => "0   chromedriver                        0x00000001075e7129 chromedriver + 3649833\n1   chromedriver                        0x0000000107577133 chromedriver + 3191091\n2   chromedriver                        0x0000000107317b42 chromedriver + 703298\n3   chromedriver                        0x0000000107284fac chromedriver + 102316\n4   chromedriver                        0x00000001072a988c chromedriver + 252044\n5   chromedriver                        0x00000001072a7bda chromedriver + 244698\n6   chromedriver                        0x00000001072a7424 chromedriver + 242724\n7   chromedriver                        0x0000000107270769 chromedriver + 18281\n8   chromedriver                        0x00000001075a4c1f chromedriver + 3378207\n9   chromedriver                        0x00000001075b0940 chromedriver + 3426624\n10  chromedriver                        0x00000001075b06d8 chromedriver + 3426008\n11  chromedriver                        0x0000000107585069 chromedriver + 3248233\n12  chromedriver                        0x00000001075b11b8 chromedriver + 3428792\n13  chromedriver                        0x0000000107598f07 chromedriver + 3329799\n14  chromedriver                        0x000000010726ea4e chromedriver + 10830\n15  libdyld.dylib                       0x00007fff62e7b3d5 start + 1\n"}, [])
                    (wallaby) lib/wallaby/driver/log_store.ex:25: Wallaby.Driver.LogStore.unique_logs/2
                    (elixir) lib/map.ex:791: Map.get_and_update/3
                    (elixir) lib/agent/server.ex:16: Agent.Server.handle_call/3
                    (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
                    (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
                    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

As I said, I believe the server is blowing up at this step for some legitimate reason (like a missing param, authorization error, etc.) but the problem is that I have absolutely no contextual information for _why_ it is blowing up.

Is this behavior expected? I was hoping to see some sort of Phoenix server stacktrace in addition to the wallaby failure, but I'm seeing literally nothing except for the error above.

I'm happy to provide a small repo to reproduce this issue, but before I go through the effort I wanted to see if this was expected or not. In the meantime, here are my chrome and chromedriver versions:

```
Chromedriver version:
ChromeDriver 76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864})

Chrome version: Version 76.0.3809.100 (Official Build) (64-bit)

Wallaby version: 0.22.0
```

Thanks so much for your help!

**Comment by mhanberg** [comment]
So the reason why the GenServer exits is due to a bug that I believe is [fixed](https://github.com/keathley/wallaby/pull/435/commits/fe029b9c0519535b2228c69c1267975513bed915#diff-5ee880815641165ab2b6af0369289c31) on master.

This is indeed masking your actual error. Do you mind trying your test using master instead of v0.22.0 and sharing what that produces?

**Comment by AndroidOatmeal** [comment]
@mhanberg Thanks so much for the quick reply! I tried master and it certainly did give me more information. Thanks for your help!

**Comment by AndroidOatmeal** [comment]
@michallepicki Do you have any plans to release this fix as a patch version?

**Comment by mhanberg** [comment]
@AndroidOatmeal we are definitely due for a release soon. This next version will probably be a minor version because it will include some new features as well.
