### ISSUE TITLE
Proposal: Enhance and standardize ability to configure WebDriver capabilities

### ISSUE THREAD

**Issue by mhanberg** [keathley/wallaby#460]
## Description

For Selenium, you can pass in the capabilities to the `start_session` function to use a custom configuration, but this is not possible using ChromeDriver.

ChromeDriver allows you to configure _some_ of the capabilities by exposing some elixir-level application configuration options.

I propose that we implement a consistent API that allows the user to pass in whatever capabilities they want, while also providing a default set of capabilities to allow a zero-configuration starting point.

This allows for more flexibility as well as opens up the possibilities that we can do with a built in FeatureCase (work for that has been started in #447).

### First-level

I propose that there is a default capabilities configuration that allows developers to get started easily using any of the drivers without needing to configure anything.

### Second-level

Second-level capabilities will be configured using application configuration and will supersede the first-level.

This will replace the configuration options used by ChromeDriver in an attempt to remain consistent with the other drivers as well as provide a transparent API that is more intuitive.

The configuration key will be the driver, so either ChromeDriver or Selenium. Since there is already a configuration option for chromedriver path, these will be moved to inside the new `:chromedriver` option.

The old option to specify the specific Chrome binary will be removed because it can be specified inside the capabilities (this is what Wallaby is doing internally).

#### Example

```elixir
config :wallaby,
  chromedriver: [ 
    path: "path/to/chromedriver",
    capabilities: %{
      # some capabilities
      chromeOptions: %{
        binary: "path/to/googlechrome"
      }
    }
  ],
  selenium: [ 
    capabilities: %{
      # some capabilities
    }
  ]
```

### Third-level

Third-level capabilities will be passed into the `start_session` function and will supersede the second-level capabilities.

#### Example

```elixir
Wallaby.start_session(
  capabilities: %{
    # some capabilities
  }
)
```

---

Let me know what you think!

cc/ @michallepicki

**Comment by michallepicki** [comment]
Similarily to the `:binary` configuration, there's also `:headless` and `:user_agent` that are also being set in capabilities. I think these are useful common options that people may want to use and I think it wouldn't be too hard to keep them. I think we could first take user-provided capabilities with fallback to default capabilities, and then for each of configured/passed options modify capabilities accordingly.
