### ISSUE TITLE
Element.text\Browser.text returns a empty string for invisible element

### ISSUE THREAD

**Issue by yonst** [keathley/wallaby#462]
## Issue

I need to get the text from invisible label but I get a empty string
elixir version 1.6.4

## Test Code & HTML

the html code:

```html
<label id="test_test"  style="display: none">test label</label>
```

the wallaby code:

```elixir
session
|> Wallaby.Browser.text(css("#test_test", visible: false))
|> IO.inspect()
```
I expected the output to be ```"test label"```, but the actual output is ```""```

**Comment by michallepicki** [comment]
@yonst I believe this is the expected output, because `text` returns visible text. You could try `Element.attr(find(css("#test_test", visible: false)), "innerHTML")` or `Element.attr(find(css("#test_test", visible: false)), "outerHTML")`

**Comment by yonst** [comment]
@michallepicki  Why ```text``` returns only the visible text if I specifically looking for invisible element? 

you right, 
 ```elixir
session
|> Element.attr( find(css("#test_test", visible: false)), "innerHTML")
|> Element.text()
|> IO.inspect()
``` 
got me the expected text.

**Comment by keathley** [comment]
@yonst I _believe_ what @michallepicki is saying is that the web browsers only returns visible text. We're using the `text` command for webdriver and that's how it works internally. There might still be some improvement to make here but that's the underlying reason iirc.

**Comment by michallepicki** [comment]
@yonst @keathley I didn't want to get too in-depth on it but yeah right now for this feature Wallaby returns whatever the WebDriver gives us. Unfortunately I don't think we can do better than that. We could try to build a better interface on top of that but it would make Wallaby a bit slower and it would probably be a development effort that we can't afford right now (For example, we wouldn't know what the "correct" response should be if the WebDriver returned something wrong. For example Safari often returns text unaffected by css `text-transform` while other WebDrivers return correct text.)

I think we could add the `"innerHTML"` attribute work-around to the documentation though

**Comment by keathley** [comment]
Adding to the docs or github wiki seems like a useful thing. I don't think we need to specifically code for this atm.
