### ISSUE TITLE
Button presses via click("<button-name>") don't register

### ISSUE THREAD

**Issue by follmann** [keathley/wallaby#47]
At least it didn't work for me, although my buttons had similar markup to the ones in `test/support/pages/forms.html`, then again there seems to be no test coverage for it either. 

I wrote an xpath that is able to find the possible range of buttons with inspiration from Capybara. 

An implementation similar to `click_link` (and as I use it) would be:
```
def press(session, button)
  button_xpath = ".//*[self::input | self::button][(./@type = 'submit' or ./@type = 'reset' or ./@type = 'button' or ./@type = 'image')][(((./@id = '#{button}' or ./@name = '#{button}' or ./@value = '#{button}' or ./@alt = '#{button}' or ./@title = '#{button}' or contains(normalize-space(string(.)), '#{button}'))))]"

  session
  |> Node.find({:xpath, button_xpath}
  |> Node.click
end
```

If desired, I can create a PR.

**Comment by keathley** [comment]
I'd love to get a PR for this! Would something like `click_button` or `click_on` make sense?

**Comment by follmann** [comment]
Sure, would make it more consistent. Alright, I will put sth together over the next days!
