### ISSUE TITLE
REST API testing

### ISSUE THREAD

**Issue by josdotso** [keathley/wallaby#48]
Hello.  I'm wondering if it makes sense to use Wallaby for REST API testing where browser testing is also needed.  Doing QA (end-to-end acceptance) testing in a standing environment with a single tool has many advantages, particularly if that tool features parallelism. Thanks!

**Comment by keathley** [comment]
I'm definitely not opposed to this. We already include httpoison as a dependency so we could expose some basic helper functions to do rest calls. However, its not a high priority for me at the moment. I'm still working on a few pieces of the API. If you would like to submit a PR I'd be happy to take a look at it though.

**Comment by keathley** [comment]
I'm going to close this for now. If its something that folks want to pursue in the future we can re-open it then.
