### ISSUE TITLE
Playing nice with authentication

### ISSUE THREAD

**Issue by lukerollans** [keathley/wallaby#57]
I can't seem to get Wallaby playing nicely with authentication. I'm using [Guardian](https://github.com/ueberauth/guardian) to handle sessions and authentication, which is obviously done through a `conn`. 

Should I ...

1. Use a helper to step Wallaby through navigating to my login form, logging in and return the altered session
2. Or; is there a way that Wallaby can play nice with a separate `conn`? If I build a conn, put the session in the state I want it to be, will the Wallaby session reflect that state? (I think this is a big no)

I'm planning on blogging this once I've figured it all out.. Seems to be a bit of a hole in the Phoenix community atm :)

**Comment by keathley** [comment]
This is a great question @lukerollans. Currently the best way to handle it is to write a helper that will go through the login steps for you. This is my preferred approach because it imitates how real users interact with your app.

You could do something like this:

```elixir
defmodule Pages.Account do
  def sign_in(session, email, password) do
    session
    |> fill_in("Email", with: email)
    |> fill_in("Password", with: password)
    |> click_button("Log In")
  end
end

defmodule SignInTest do
  use ExUnit.Case, async: true

  alias Pages.Account

  test "users can sign in", %{session: session} do
    session
    |> Account.sign_in(session, "email@example.com", "password")

    # ...
  end
end
```

We can't expose the conn in the test, since all of that is going to be driven from the browser. But we could give you access to set cookies and such through Wallaby's api. Setting cookies is supported by webdriver but we haven't implemented those features yet. They're straightforward to implement though. Once we had access to cookies we could generate a token and stuff it into a cookie as a way to "fake" logging in. Personally I would only use this if there was no way to test with a real login flow though. If we needed to do anything more complicated then we would have to do it through javascript. This is possible with the current Wallaby api but would be more tedious.

**Comment by lukerollans** [comment]
@keathley as I thought, thanks for taking the time to reply

**Comment by brandonparsons** [comment]
@lukerollans Is there a way now to interact /w browser cookies through Wallaby?

While I agree with you that a real user's flow through the login page must be tested, you really only need to do this once. If you have a test that proves a user can successfully log in, it seems wasteful to do that on _every single test_. Would prefer to be able to drop in a cookie on the remainder of tests.

**Comment by brandonparsons** [comment]
Poking around a bit I've found https://github.com/keathley/wallaby/blob/master/lib/wallaby/browser.ex#L1033 . It doesn't show up in the official documentation, but I'm assuming I can use this?

**Comment by keathley** [comment]
@brandonparsons retrieving and setting cookies is supported in master right now. It'll be available in the next release.

As a side note, projects I've had in the past have had some issues with logging in with cookies. It works well at first but if your auth starts to change it can cause issues. Typically I just default to always logging in the user. But thats just like, my opinion, man. In the next version you'll be able to make your own choices :)

**Comment by brandonparsons** [comment]
@keathley Fair enough. I was slowly coming to that conclusion after fighting with Phoenix for a few hours just trying to get it to do what I want with the session cookie haha :)

**Comment by PJUllrich** [comment]
I bumped into this issue again and wanted to share my (hacky) solution. I'm absolutely not sure whether this is a secure way, so comments on that are highly appreciated.

## WARNING: POSSIBLY VERY INSECURE

The core of the solution is creating an extra endpoint, which is only exposed during testing. So, add this to your `router.ex`:

```elixir
if Mix.env() == :test do
    get("/:user_id", AuthController, :test_login)
end
```

Then, in your `AuthController` (or where ever you handle the Guardian `callbacks`), add a `test_login(conn, %{"user_id" => user_id})` function, which contains all the authentication logic, which your normal `callback` function contains. For example:

```elixir
def test_login(conn, %{"user_id" => user_id}) do
     {:ok, session} = Repo.update_session(conn.assigns.session, %{user_id: user_id})

    conn
    |> assign(:session, session)
    |> redirect(to: Routes.home_path(conn, :index))
end
```

**Comment by PragTob** [comment]
@PJUllrich I use a similar solution. I make it a completely separate controller though and also wrap the controller module itself in `if Mix.env() == :test` - that way it's not just blocked out in the controller but the code never makes it into a release. It also has 2 fail save switches so one can get knocked out but people won't be able to randomly login still.

**Comment by Preen** [comment]
I did the same as @PJUllrich and @PragTob, works well. I put the password as env in the test. This allowed us to use the same login sequence as an ordinary call. However, it requires one to populate the DB with the same user password as the one you use in the env below.

Controller:

```
  if Mix.env() == :test do
    def test_login(conn, %{"user_id" => user_id}) do
      user = Db.Repo.get(User, user_id)
      User.authenticate(%{email: user.email, password: Application.get_env(:admin, :test_password)})
      |> login_reply(conn, 0)
    end
  end
```

Test:

```
    user_params = params_for(:user,
      password: Application.get_env(:admin, :test_password),
      ...
    )

    {:ok, user} = %User{}
    |> User.changeset(user_params)
    |> Repo.insert()

    session
    |> visit("/test/sessions/#{user.id}")
    |> ...
```

**Comment by jorbs** [comment]
For those using Ueberauth (I am using UeberauthAuth0), I needed to create a plug like below:

```
defmodule Ueberauth.Strategy.Auth0Test do
  use Ueberauth.Strategy

  def handle_request!(conn) do
    handle_callback!(conn)
  end

  def handle_callback!(conn) do
    auth = %Ueberauth.Auth{
      uid: "google-oauth2|lyy5v4523323bn943qf",
      provider: "auth0",
      info: %Ueberauth.Auth.Info{
        name: "Jane Josephine Doe",
        first_name: "Jane",
        last_name: "Doe",
        nickname: "JJ",
        email: "janedoe@acme.com",
        location: "us",
        birthday: "1988-08-06"
      }
    }

    assign(conn, :ueberauth_auth, auth)
  end

  def handle_cleanup!(conn) do
    assign(conn, :ueberauth_auth, nil)
  end
end
```

And set it in `test.exs`:

```
config :ueberauth, Ueberauth,
  providers: [
    auth0: {Ueberauth.Strategy.Auth0Test, []}
  ]
```

I am not sure if that's the correct way to mock, but at least it works fine in my tests.
