### ISSUE TITLE
Unable to chain `fill_in`?

### ISSUE THREAD

**Issue by lukerollans** [keathley/wallaby#59]
Slightly related to a previous issue, I'm trying to create a helper that steps through user sign in's.

`Esteem.UserHelper.sign_in/3` is only ever invoked from another module which is using `AcceptanceCase`

```elixir
defmodule Esteem.UserHelper do
  use Wallaby.DSL

  def sign_in(session, email, password) do
    session
    |> visit("/sessions/new")
    |> fill_in("Your email", with: email)
    |> fill_in("Password", with: password)
    |> click_button("Submit")
  end
end
```

When it runs, I get the following error

```
  1) test user signs out and is redirected to login page (Esteem.UserSessionsTest)
     test/acceptance/user_sessions_test.exs:16
     ** (FunctionClauseError) no function clause matching in Wallaby.DSL.Actions.fill_in/3
     stacktrace:
       (wallaby) lib/wallaby/dsl/actions.ex:59: Wallaby.DSL.Actions.fill_in(%Wallaby.Session{base_url: "http://localhost:65372/", id: "195cd7d0-3f74-11e6-b0d4-d76992d84dcf", screenshots: [], server: #PID<0.467.0>}, "Password", [with: 'test'])
       (esteem) test/support/user_helper.ex:8: Esteem.UserHelper.sign_in/3
       test/acceptance/user_sessions_test.exs:18
```

It seems that the second `fill_in` (in this case, "Password") is getting a clause error.. and I honestly have no idea why.

Here is another test in the suite that works just fine, so I don't know why chaining `fill_in`'s would be an issue

```
defmodule Esteem.UserSignsUpTest do
  use Esteem.AcceptanceCase, async: true

  test "user signs up", %{session: session} do
    session
    |> visit("/")
    |> fill_in("First name", with: "Luke")
    |> fill_in("Last name", with: "Rollans")
    |> fill_in("Email", with: "hello@lukerollans.me")
    |> fill_in("Password", with: "123456")
    |> fill_in("Organisation name", with: "Marvellous Mutants")
    |> click_button("Submit")

    notice =
      session
      |> find(".alert-info")
      |> text

    assert notice == "Signed up successfully!"
  end
end
```

I am really sorry to post again, but I just don't know how to proceed.. and hopefully this might help someone else in future :)

**Comment by keathley** [comment]
No worries @lukerollans :)

It looks like your `password` argument in your `sign_in` helper is coming in as a char list:

```
(wallaby) lib/wallaby/dsl/actions.ex:59: Wallaby.DSL.Actions.fill_in(%Wallaby.Session{base_url: "http://localhost:65372/", id: "195cd7d0-3f74-11e6-b0d4-d76992d84dcf", screenshots: [], server: #PID<0.467.0>}, "Password", [with: 'test'])
```

`fill_in` expects a binary and enforces that with a guard clause. Hence why you would be getting a "no clause" error. I suspect that if you change your password to a string it'll solve the problem. If that doesn't work could you post the html as well so I can try running things locally?

**Comment by lukerollans** [comment]
Definitely shows how new I am to Elixir :) Thanks again!
