### ISSUE TITLE
HTTPoison timeout

### ISSUE THREAD

**Issue by stevegraham** [keathley/wallaby#74]
I'm having some tests fail intermittently because of a HTTPPoison timeout error. Would you be open to setting the HTTPoison timeout to `:infinity` as ExUnit.Case already has a configurable timeout with a default?

EDIT: Adding some more information.

- This only happens when running my Wallaby tests on their own, e.g. `mix test test/features` 
- It's always the first or second test.

This makes me think it's actually the first test running before everything is fully initialised (phantom?), so setting HTTPoison mike not be the best way to fix in your opinion.

**Comment by keathley** [comment]
There are a couple things that could be causing this. It *shouldn't* be possible to checkout a phantom before its started. A more likely solution is that its the phoenix server booting up / building assets. I'm not opposed to setting a longer timeout for httpoison though. Its probably better to return a more meaningful error from Wallaby anyway. Either way it would be worth digging into a bit to see exactly whats going on.

**Comment by aaronjensen** [comment]
We hit this too due to webpack building assets.

**Comment by keathley** [comment]
Would you mind submitting a PR for this? I won't be able to get to it for a few days.

**Comment by steve0hh** [comment]
I've had this error and made a fork of this project.

Basically i did the following:

```
  defp make_request(method, url, body) do
    headers = [{"Content-Type", "text/json"}]
    case HTTPoison.request(method, url, body, headers, [timeout: :infinity, recv_timeout: :infinity]) do
      {:ok, response} ->
        Poison.decode!(response.body)
      {:error, e} ->
        raise "There was an error calling: #{url} -> #{e.reason}"
    end
  end

```

Essential just setting both poison options : `[timeout: :infinity, recv_timeout: :infinity] `.

It solves the timeout issue.

If you guys are ok, I could submit a PR.

**Comment by keathley** [comment]
Please do.
