### ISSUE TITLE
File upload?

### ISSUE THREAD

**Issue by stevegraham** [keathley/wallaby#75]
Has file uploading been implemented in Wallaby? I looked but didn't see anything that would match a file input in xpath.ex nor did I see anything in the docs to indicate support.

**Comment by stevegraham** [comment]
I ended up hacking this up for my test case like this and it works great.

```elixir
  def attach_file(session, locator, [{:file, value} | _] = opts) when is_binary(value) do
    alias Wallaby.Node

    query = ".//input[./@type = 'file'][(((./@id = '#{locator}' or ./@name = '#{locator}') or ./@placeholder = '#{locator}') or ./@id = //label[contains(normalize-space(string(.)), '#{locator}')]/@for)] | .//label[contains(normalize-space(string(.)), '#{locator}')]//.//input[./@type = 'file']"
    file = :filename.absname(value)
    session
    |> Node.Query.find({:xpath, query}, opts)
    |> Node.fill_in(with: file)

    session
  end
```

Would you be open to a PR… Done properly like the rest of the DSL of course! 😂

**Comment by keathley** [comment]
This would be great. Would love to see a PR :+1:

**Comment by stratigos** [comment]
Id like to use this feature, but the "documentation" refers to an element named `page`, and all I  know of that is available is `session`. 

How is the `page` found / derived / loaded, etc? Where can one find complete examples that show exactly how this can be used?

**Comment by mhanberg** [comment]
Please open a discussion instead of commenting on an old PR
