### ISSUE TITLE
can't call text with a session

### ISSUE THREAD

**Issue by keathley** [keathley/wallaby#96]
If you pass a session to text it returns an `Invalid command` from Webdriver:

``` elixir
session
|> visit("/")
|> text
```

**Comment by kopchickm** [comment]
OK, I was able to get this error again when filling out a form.  Should I be doing this in a different way?

```
  test "a user can't submit an upload without a data file", %{session: session} do
    page_text  =
      session
      |> visit("/files/new")
      |> fill_in("Monitor Number", with: "123")
      |> fill_in("Latitude", with: "123")
      |> fill_in("Longitude", with: "456")
      |> click_on("Submit")
      |> text
    assert String.contains?(page_text, "Couldn't upload file. Please fix errors and try again")
```

**Comment by keathley** [comment]
@kopchickm I'm working on a fix for this. The root cause is that text expects a `Node`. If you wanna fix this for now you can use a specific `find` after the `click_on` like:

```elixir
click_on("submit")
|> find(".alert")
|> text
```

I have a fix for this which should be merge-able soon.

**Comment by keathley** [comment]
This is now fixed in master.

**Comment by kopchickm** [comment]
Woohoo!
