### ISSUE TITLE
Automatic screenshots don't appear to work

### ISSUE THREAD

**Issue by jerel** [keathley/wallaby#98]
I've added the config

``` ex
# config/test.exs
config :wallaby, screenshot_on_failure: true
```

to my app but when I do `assert "foo" == "bar"` no screenshot is taken. Screenshots in general do work though as adding `take_screenshot(session)` to the same test does result in a screenshot.

Let me know if there is additional debug information needed. I've just started with wallaby so it's not impossible that I'm doing something wrong.

**Comment by keathley** [comment]
Sorry about that @jerel. This is a good catch. Currently Wallaby can't catch all test failures. It can only catch failures that occur through using the api. That config flag is poorly named and should probably be changed to something like, `screenshot_on_error`. I'm also working on adding a `feature` test type. That will allow us to write tests like:

```elixir
feature "it does some stuff" do
#...
end
```

The custom type will allow us to capture screenshots with all test failures.

Hopefully that makes sense. I'm really sorry about the confusion.

**Comment by keathley** [comment]
I've opened a specific issue for creating a `feature` case in #142.
